-- Granica konta sięga korzeni pracy Operatora.
--
-- Wskazanie konta stoi w tabeli, której wiersz należy do Operatora wprost.
-- Wiersz wiszący na takim korzeniu kluczem obcym granicę dziedziczy drogą po
-- tym kluczu i własnego wskazania nie dostaje: to samo rozstrzygnięcie zapisane
-- dwa razy rozjeżdża się przy pierwszej zmianie właściciela.
--
-- Kolumna dopuszcza NULL i nie ma klucza obcego. Wiersze zastane powstały przed
-- rozdzieleniem kont i nie mają jak wskazać konta wstecz; brak wskazania czyta
-- się jako konto najstarsze, tak samo jak w tabelach bramki (migracja 406)
-- i w kartach sesji (migracja 407).
--
-- Wskaźnika na samą kolumnę krok nie zakłada: w instalacji jednokontowej niesie
-- ona jedną wartość, a zapytania zawężają się kontem wraz z kluczem własnym
-- tabeli. Wskaźnik wchodzi krokiem osobnym tam, gdzie wskaże go pomiar.
--
-- Tabela `kanal_modelu` wskazania nie dostaje: niesie je od migracji 001.

ALTER TABLE agent ADD COLUMN konto_id INTEGER;
ALTER TABLE architektura_apps ADD COLUMN konto_id INTEGER;
ALTER TABLE artefakt_apps ADD COLUMN konto_id INTEGER;
ALTER TABLE automatyka ADD COLUMN konto_id INTEGER;
ALTER TABLE autozamiana_znaku_studio ADD COLUMN konto_id INTEGER;
ALTER TABLE blok_wiadomosci ADD COLUMN konto_id INTEGER;
ALTER TABLE debata_artefakt ADD COLUMN konto_id INTEGER;
ALTER TABLE debata_glosowanie ADD COLUMN konto_id INTEGER;
ALTER TABLE debata_katalog_okna ADD COLUMN konto_id INTEGER;
ALTER TABLE debata_macierz ADD COLUMN konto_id INTEGER;
ALTER TABLE debata_ocena ADD COLUMN konto_id INTEGER;
ALTER TABLE debata_ranking ADD COLUMN konto_id INTEGER;
ALTER TABLE debata_rubryka ADD COLUMN konto_id INTEGER;
ALTER TABLE debata_stanowisko ADD COLUMN konto_id INTEGER;
ALTER TABLE debata_szablon ADD COLUMN konto_id INTEGER;
ALTER TABLE debata_tura ADD COLUMN konto_id INTEGER;
ALTER TABLE debata_uczestnik ADD COLUMN konto_id INTEGER;
ALTER TABLE debata_ustalenie ADD COLUMN konto_id INTEGER;
ALTER TABLE debata_werdykt ADD COLUMN konto_id INTEGER;
ALTER TABLE debata_wezel ADD COLUMN konto_id INTEGER;
ALTER TABLE debata_zdanie_odrebne ADD COLUMN konto_id INTEGER;
ALTER TABLE debata_zespol ADD COLUMN konto_id INTEGER;
ALTER TABLE developer_budowanie ADD COLUMN konto_id INTEGER;
ALTER TABLE developer_kolekcja_api ADD COLUMN konto_id INTEGER;
ALTER TABLE developer_polaczenie_danych ADD COLUMN konto_id INTEGER;
ALTER TABLE developer_punkt_przerwania ADD COLUMN konto_id INTEGER;
ALTER TABLE developer_skan ADD COLUMN konto_id INTEGER;
ALTER TABLE developer_wersja_pliku ADD COLUMN konto_id INTEGER;
ALTER TABLE diagnostyka_analiza ADD COLUMN konto_id INTEGER;
ALTER TABLE diagnostyka_blad ADD COLUMN konto_id INTEGER;
ALTER TABLE diagnostyka_wpis ADD COLUMN konto_id INTEGER;
ALTER TABLE dokument_studio ADD COLUMN konto_id INTEGER;
ALTER TABLE dziennik_zdarzen ADD COLUMN konto_id INTEGER;
ALTER TABLE etap_apps ADD COLUMN konto_id INTEGER;
ALTER TABLE etap_przestrzeni_badania ADD COLUMN konto_id INTEGER;
ALTER TABLE etykieta_slownika_biblioteki ADD COLUMN konto_id INTEGER;
ALTER TABLE fragment_wiedzy ADD COLUMN konto_id INTEGER;
ALTER TABLE granica_wykonawcy_przegladania ADD COLUMN konto_id INTEGER;
ALTER TABLE grupa_kart_przegladania ADD COLUMN konto_id INTEGER;
ALTER TABLE historia_rozszerzenia ADD COLUMN konto_id INTEGER;
ALTER TABLE host_zdalny ADD COLUMN konto_id INTEGER;
ALTER TABLE ikona_design ADD COLUMN konto_id INTEGER;
ALTER TABLE integracja_rozszerzenia ADD COLUMN konto_id INTEGER;
ALTER TABLE kamien_milowy_apps ADD COLUMN konto_id INTEGER;
ALTER TABLE kanal_przegladania ADD COLUMN konto_id INTEGER;
ALTER TABLE karta_przegladania ADD COLUMN konto_id INTEGER;
ALTER TABLE kod_badania ADD COLUMN konto_id INTEGER;
ALTER TABLE kolekcja_biblioteki ADD COLUMN konto_id INTEGER;
ALTER TABLE kolekcja_design ADD COLUMN konto_id INTEGER;
ALTER TABLE kolekcja_rozszerzen ADD COLUMN konto_id INTEGER;
ALTER TABLE komponent ADD COLUMN konto_id INTEGER;
ALTER TABLE komponent_design ADD COLUMN konto_id INTEGER;
ALTER TABLE kompozycja_design ADD COLUMN konto_id INTEGER;
ALTER TABLE kondycja_rozszerzenia ADD COLUMN konto_id INTEGER;
ALTER TABLE kondycja_wdrozenia_apps ADD COLUMN konto_id INTEGER;
ALTER TABLE konsultacja_doradcy ADD COLUMN konto_id INTEGER;
ALTER TABLE kontekst_pamieci ADD COLUMN konto_id INTEGER;
ALTER TABLE konto ADD COLUMN konto_id INTEGER;
ALTER TABLE lancuch_studio ADD COLUMN konto_id INTEGER;
ALTER TABLE makro_przegladania ADD COLUMN konto_id INTEGER;
ALTER TABLE mapowanie_rozszerzenia ADD COLUMN konto_id INTEGER;
ALTER TABLE migawka_strony ADD COLUMN konto_id INTEGER;
ALTER TABLE monitor_badania ADD COLUMN konto_id INTEGER;
ALTER TABLE monitor_przegladania ADD COLUMN konto_id INTEGER;
ALTER TABLE motyw_apps ADD COLUMN konto_id INTEGER;
ALTER TABLE nagranie_mowy ADD COLUMN konto_id INTEGER;
ALTER TABLE nastawa_fotografii_design ADD COLUMN konto_id INTEGER;
ALTER TABLE notatka_przegladania ADD COLUMN konto_id INTEGER;
ALTER TABLE odwolanie_wersji_studio ADD COLUMN konto_id INTEGER;
ALTER TABLE okno_tlumaczenia ADD COLUMN konto_id INTEGER;
ALTER TABLE operacja_studio ADD COLUMN konto_id INTEGER;
ALTER TABLE paczka_rozszerzenia ADD COLUMN konto_id INTEGER;
ALTER TABLE pakiet_apps ADD COLUMN konto_id INTEGER;
ALTER TABLE plik_biblioteki ADD COLUMN konto_id INTEGER;
ALTER TABLE plik_warsztatu_apps ADD COLUMN konto_id INTEGER;
ALTER TABLE pobranie_przegladania ADD COLUMN konto_id INTEGER;
ALTER TABLE podglad_apps ADD COLUMN konto_id INTEGER;
ALTER TABLE podobienstwo_obrazu ADD COLUMN konto_id INTEGER;
ALTER TABLE polityka_pivota ADD COLUMN konto_id INTEGER;
ALTER TABLE polityka_retencji_biblioteki ADD COLUMN konto_id INTEGER;
ALTER TABLE postac_malarza_studio ADD COLUMN konto_id INTEGER;
ALTER TABLE poswiadczenie_automatyki ADD COLUMN konto_id INTEGER;
ALTER TABLE powiadomienie ADD COLUMN konto_id INTEGER;
ALTER TABLE powiadomienie_centrum ADD COLUMN konto_id INTEGER;
ALTER TABLE pozycja_czytania_przegladania ADD COLUMN konto_id INTEGER;
ALTER TABLE pozycja_wczytywania_studio ADD COLUMN konto_id INTEGER;
ALTER TABLE produkt_apps ADD COLUMN konto_id INTEGER;
ALTER TABLE profil_asystenta ADD COLUMN konto_id INTEGER;
ALTER TABLE profil_druku_design ADD COLUMN konto_id INTEGER;
ALTER TABLE profil_izolacji ADD COLUMN konto_id INTEGER;
ALTER TABLE profil_qa ADD COLUMN konto_id INTEGER;
ALTER TABLE profil_silnika_tlumaczenia ADD COLUMN konto_id INTEGER;
ALTER TABLE profil_wydania_studio ADD COLUMN konto_id INTEGER;
ALTER TABLE projekt ADD COLUMN konto_id INTEGER;
ALTER TABLE prompt_design ADD COLUMN konto_id INTEGER;
ALTER TABLE prowenancja_badania ADD COLUMN konto_id INTEGER;
ALTER TABLE prowenancja_odcinek ADD COLUMN konto_id INTEGER;
ALTER TABLE prowenancja_wywolanie ADD COLUMN konto_id INTEGER;
ALTER TABLE przestrzen_badania ADD COLUMN konto_id INTEGER;
ALTER TABLE przestrzen_przegladania ADD COLUMN konto_id INTEGER;
ALTER TABLE punkt_dostepu ADD COLUMN konto_id INTEGER;
ALTER TABLE pytanie_badania ADD COLUMN konto_id INTEGER;
ALTER TABLE regula_alertu ADD COLUMN konto_id INTEGER;
ALTER TABLE regula_biblioteki ADD COLUMN konto_id INTEGER;
ALTER TABLE rodzaj_znacznika_studio ADD COLUMN konto_id INTEGER;
ALTER TABLE rozszerzenie ADD COLUMN konto_id INTEGER;
ALTER TABLE sekcja_panelu ADD COLUMN konto_id INTEGER;
ALTER TABLE sekret_rozszerzenia ADD COLUMN konto_id INTEGER;
ALTER TABLE skalowanie_apps ADD COLUMN konto_id INTEGER;
ALTER TABLE skrot_tekstowy ADD COLUMN konto_id INTEGER;
ALTER TABLE skrzynka_pocztowa ADD COLUMN konto_id INTEGER;
ALTER TABLE slad_eksportu_slownika ADD COLUMN konto_id INTEGER;
ALTER TABLE slad_importu_slownika ADD COLUMN konto_id INTEGER;
ALTER TABLE sonda_kondycji ADD COLUMN konto_id INTEGER;
ALTER TABLE sprzecznosc_badania ADD COLUMN konto_id INTEGER;
ALTER TABLE srodowisko_apps ADD COLUMN konto_id INTEGER;
ALTER TABLE styl_cytowania_badania ADD COLUMN konto_id INTEGER;
ALTER TABLE sugestia_biblioteki ADD COLUMN konto_id INTEGER;
ALTER TABLE sygnal_nakladki ADD COLUMN konto_id INTEGER;
ALTER TABLE szablon_automatyki ADD COLUMN konto_id INTEGER;
ALTER TABLE szablon_eksportu_badania ADD COLUMN konto_id INTEGER;
ALTER TABLE szablon_materialu_design ADD COLUMN konto_id INTEGER;
ALTER TABLE szablon_promptu_design ADD COLUMN konto_id INTEGER;
ALTER TABLE szablon_raportu_badania ADD COLUMN konto_id INTEGER;
ALTER TABLE szablon_studio ADD COLUMN konto_id INTEGER;
ALTER TABLE termin_slownika ADD COLUMN konto_id INTEGER;
ALTER TABLE terminal_host ADD COLUMN konto_id INTEGER;
ALTER TABLE terminal_karta ADD COLUMN konto_id INTEGER;
ALTER TABLE terminal_klucz ADD COLUMN konto_id INTEGER;
ALTER TABLE terminal_obserwacja ADD COLUMN konto_id INTEGER;
ALTER TABLE terminal_proces ADD COLUMN konto_id INTEGER;
ALTER TABLE terminal_skrypt ADD COLUMN konto_id INTEGER;
ALTER TABLE terminal_tunel ADD COLUMN konto_id INTEGER;
ALTER TABLE transkrypcja ADD COLUMN konto_id INTEGER;
ALTER TABLE udostepnienie_biblioteki ADD COLUMN konto_id INTEGER;
ALTER TABLE uprawnienie_rozszerzenia ADD COLUMN konto_id INTEGER;
ALTER TABLE urzadzenie_powiadomien ADD COLUMN konto_id INTEGER;
ALTER TABLE ustalenie_badania ADD COLUMN konto_id INTEGER;
ALTER TABLE ustawienie ADD COLUMN konto_id INTEGER;
ALTER TABLE warstwa_izolacji ADD COLUMN konto_id INTEGER;
ALTER TABLE watek_notatek_przegladania ADD COLUMN konto_id INTEGER;
ALTER TABLE watek_ustalen_badania ADD COLUMN konto_id INTEGER;
ALTER TABLE wdrozenie_apps ADD COLUMN konto_id INTEGER;
ALTER TABLE webhook_biblioteki ADD COLUMN konto_id INTEGER;
ALTER TABLE webhook_rozszerzenia ADD COLUMN konto_id INTEGER;
ALTER TABLE wersja_rozszerzenia ADD COLUMN konto_id INTEGER;
ALTER TABLE wiersz_dziennika_apps ADD COLUMN konto_id INTEGER;
ALTER TABLE wpis_audytu_biblioteki ADD COLUMN konto_id INTEGER;
ALTER TABLE wpis_schowka ADD COLUMN konto_id INTEGER;
ALTER TABLE wyciszenie_nakladki ADD COLUMN konto_id INTEGER;
ALTER TABLE wynik_odkrycia_badania ADD COLUMN konto_id INTEGER;
ALTER TABLE wytwor_przegladania ADD COLUMN konto_id INTEGER;
ALTER TABLE wywolanie_rozszerzenia ADD COLUMN konto_id INTEGER;
ALTER TABLE zadanie_utrwalenia_biblioteki ADD COLUMN konto_id INTEGER;
ALTER TABLE zakladka_przegladania ADD COLUMN konto_id INTEGER;
ALTER TABLE zamkniecie_tury ADD COLUMN konto_id INTEGER;
ALTER TABLE zasada_przechowywania ADD COLUMN konto_id INTEGER;
ALTER TABLE zasada_retencji_pamieci ADD COLUMN konto_id INTEGER;
ALTER TABLE zasob_design ADD COLUMN konto_id INTEGER;
ALTER TABLE zasob_pamieci ADD COLUMN konto_id INTEGER;
ALTER TABLE zdalne_przeniesienie ADD COLUMN konto_id INTEGER;
ALTER TABLE zespol ADD COLUMN konto_id INTEGER;
ALTER TABLE zestaw_regul_segmentacji ADD COLUMN konto_id INTEGER;
ALTER TABLE zestaw_zetonow_design ADD COLUMN konto_id INTEGER;
ALTER TABLE zestaw_zrodel_przegladania ADD COLUMN konto_id INTEGER;
ALTER TABLE zlecenie_asystenta ADD COLUMN konto_id INTEGER;
ALTER TABLE zmienna_srodowiska_apps ADD COLUMN konto_id INTEGER;
ALTER TABLE znak_ostatnio_uzyty_studio ADD COLUMN konto_id INTEGER;
ALTER TABLE zrodlo_badania ADD COLUMN konto_id INTEGER;
ALTER TABLE zrodlo_przegladania ADD COLUMN konto_id INTEGER;
ALTER TABLE zrzut_przegladania ADD COLUMN konto_id INTEGER;
