// Katalog czynności warsztatów Design przeniesiony z poprzedniego klienta:
// nazwa komendy, pola żądania i sposób ich złożenia. Widok nie idzie stamtąd —
// pola stają w węzłach prototypu.

import { Command } from '../../../shared/contract.ts';

export type GrupaWarsztatu = 'fotografia' | 'wektor' | 'druk' | 'bazy' | 'publikacja' | 'makieta';

export type PostacPola = 'tekst' | 'liczba' | 'logiczne' | 'lista' | 'listaLiczb' | 'obszary' | 'json';

export interface PoleCzynnosci {
  kod: string;
  etykieta: string;
  rodzaj: 'tekst' | 'liczba' | 'logiczne' | 'wybor' | 'wielowiersz' | 'zasob' | 'zasoby';
  postac: PostacPola;
  wymagane?: boolean;
  gniazdo?: string;
  pozycje?: readonly { wartosc: string; etykieta: string }[];
}

export interface CzynnoscDesignu {
  grupa: GrupaWarsztatu;
  komenda: Command;
  nazwa: string;
  okno: boolean;
  pola: readonly PoleCzynnosci[];
}

export const CZYNNOSCI_DESIGNU: readonly CzynnoscDesignu[] = [
  {
    grupa: 'fotografia',
    komenda: Command.DesignPhotoCrop,
    nazwa: 'Kadruj i prostuj',
    okno: true,
    pola: [
      { kod: 'x', etykieta: 'Lewy brzeg kadru (px)', rodzaj: 'liczba', postac: 'liczba' },
      { kod: 'y', etykieta: 'Górny brzeg kadru (px)', rodzaj: 'liczba', postac: 'liczba' },
      { kod: 'width', etykieta: 'Szerokość kadru (px)', rodzaj: 'liczba', postac: 'liczba' },
      { kod: 'height', etykieta: 'Wysokość kadru (px)', rodzaj: 'liczba', postac: 'liczba' },
      { kod: 'aspectRatio', etykieta: 'Proporcje kadru', rodzaj: 'wybor', postac: 'tekst',
        pozycje: [
          { wartosc: '', etykieta: 'bez zmiany' },
          { wartosc: '1:1', etykieta: '1:1 — kwadrat' },
          { wartosc: '4:5', etykieta: '4:5 — pion społecznościowy' },
          { wartosc: '16:9', etykieta: '16:9 — panorama' },
          { wartosc: '3:2', etykieta: '3:2 — klatka małoobrazkowa' },
        ] },
      { kod: 'straightenDeg', etykieta: 'Prostowanie horyzontu (°)', rodzaj: 'liczba', postac: 'liczba' },
      { kod: 'assetId', etykieta: 'Materiał', rodzaj: 'zasob', postac: 'tekst', wymagane: true },
    ],
  },
  {
    grupa: 'fotografia',
    komenda: Command.DesignPhotoTransform,
    nazwa: 'Obróć, odbij, wyprostuj perspektywę',
    okno: true,
    pola: [
      { kod: 'rotateDeg', etykieta: 'Obrót (°)', rodzaj: 'liczba', postac: 'liczba' },
      { kod: 'flipHorizontal', etykieta: 'Odbij w poziomie', rodzaj: 'logiczne', postac: 'logiczne' },
      { kod: 'flipVertical', etykieta: 'Odbij w pionie', rodzaj: 'logiczne', postac: 'logiczne' },
      { kod: 'lensDistortion', etykieta: 'Korekcja obiektywu', rodzaj: 'liczba', postac: 'liczba' },
      { kod: 'perspective', etykieta: 'Naroża po korekcji perspektywy', rodzaj: 'wielowiersz', postac: 'tekst' },
      { kod: 'assetId', etykieta: 'Materiał', rodzaj: 'zasob', postac: 'tekst', wymagane: true },
    ],
  },
  {
    grupa: 'fotografia',
    komenda: Command.DesignPhotoResample,
    nazwa: 'Przelicz rozdzielczość',
    okno: true,
    pola: [
      { kod: 'width', etykieta: 'Szerokość docelowa (px)', rodzaj: 'liczba', postac: 'liczba' },
      { kod: 'height', etykieta: 'Wysokość docelowa (px)', rodzaj: 'liczba', postac: 'liczba' },
      { kod: 'filter', etykieta: 'Filtr', rodzaj: 'wybor', postac: 'tekst',
        pozycje: [
          { wartosc: '', etykieta: 'Lanczos (domyślnie)' },
          { wartosc: 'lanczos', etykieta: 'Lanczos — najostrzejszy' },
          { wartosc: 'bilinear', etykieta: 'Dwuliniowy — łagodny' },
          { wartosc: 'nearest', etykieta: 'Najbliższy sąsiad — twarde piksele' },
        ] },
      { kod: 'keepAspectRatio', etykieta: 'Zachowaj proporcje', rodzaj: 'logiczne', postac: 'logiczne' },
      { kod: 'assetId', etykieta: 'Materiał', rodzaj: 'zasob', postac: 'tekst', wymagane: true },
    ],
  },
  {
    grupa: 'fotografia',
    komenda: Command.DesignPhotoUpscale,
    nazwa: 'Powiększ',
    okno: true,
    pola: [
      { kod: 'factor', etykieta: 'Krotność', rodzaj: 'wybor', postac: 'liczba', wymagane: true,
        pozycje: [
          { wartosc: '2', etykieta: '2×' },
          { wartosc: '4', etykieta: '4×' },
          { wartosc: '8', etykieta: '8×' },
        ] },
      { kod: 'sharpenAfter', etykieta: 'Wyostrz po powiększeniu', rodzaj: 'logiczne', postac: 'logiczne' },
      { kod: 'assetId', etykieta: 'Materiał', rodzaj: 'zasob', postac: 'tekst', wymagane: true },
      { kod: 'channelId', etykieta: 'Kanał modelu obrazowego', rodzaj: 'tekst', postac: 'tekst' },
    ],
  },
  {
    grupa: 'fotografia',
    komenda: Command.DesignPhotoEnhance,
    nazwa: 'Popraw jakość',
    okno: true,
    pola: [
      { kod: 'autoLevels', etykieta: 'Auto-poziomy', rodzaj: 'logiczne', postac: 'logiczne' },
      { kod: 'autoContrast', etykieta: 'Auto-kontrast', rodzaj: 'logiczne', postac: 'logiczne' },
      { kod: 'denoise', etykieta: 'Odszumienie (0–1)', rodzaj: 'liczba', postac: 'liczba' },
      { kod: 'sharpen', etykieta: 'Wyostrzenie (0–1)', rodzaj: 'liczba', postac: 'liczba' },
      { kod: 'assetId', etykieta: 'Materiał', rodzaj: 'zasob', postac: 'tekst', wymagane: true },
    ],
  },
  {
    grupa: 'fotografia',
    komenda: Command.DesignPhotoColorCorrect,
    nazwa: 'Koryguj barwę',
    okno: true,
    pola: [
      { kod: 'brightness', etykieta: 'Jasność (−1…1)', rodzaj: 'liczba', postac: 'liczba' },
      { kod: 'contrast', etykieta: 'Kontrast (−1…1)', rodzaj: 'liczba', postac: 'liczba' },
      { kod: 'exposure', etykieta: 'Ekspozycja (działki)', rodzaj: 'liczba', postac: 'liczba' },
      { kod: 'temperature', etykieta: 'Temperatura barwowa (−1…1)', rodzaj: 'liczba', postac: 'liczba' },
      { kod: 'gamma', etykieta: 'Gamma', rodzaj: 'liczba', postac: 'liczba' },
      { kod: 'saturation', etykieta: 'Nasycenie (−1…1)', rodzaj: 'liczba', postac: 'liczba' },
      { kod: 'hueShiftDeg', etykieta: 'Przesunięcie odcienia (°)', rodzaj: 'liczba', postac: 'liczba' },
      { kod: 'lightness', etykieta: 'Jasność percepcyjna (−1…1)', rodzaj: 'liczba', postac: 'liczba' },
      { kod: 'curves', etykieta: 'Krzywe tonalne', rodzaj: 'wielowiersz', postac: 'json' },
      { kod: 'assetId', etykieta: 'Materiał', rodzaj: 'zasob', postac: 'tekst', wymagane: true },
    ],
  },
  {
    grupa: 'fotografia',
    komenda: Command.DesignPhotoFilterApply,
    nazwa: 'Nałóż filtr',
    okno: true,
    pola: [
      { kod: 'filter', etykieta: 'Filtr', rodzaj: 'wybor', postac: 'tekst', wymagane: true,
        pozycje: [
          { wartosc: '', etykieta: 'Lanczos (domyślnie)' },
          { wartosc: 'lanczos', etykieta: 'Lanczos — najostrzejszy' },
          { wartosc: 'bilinear', etykieta: 'Dwuliniowy — łagodny' },
          { wartosc: 'nearest', etykieta: 'Najbliższy sąsiad — twarde piksele' },
        ] },
      { kod: 'amount', etykieta: 'Siła (0–1)', rodzaj: 'liczba', postac: 'liczba' },
      { kod: 'assetId', etykieta: 'Materiał', rodzaj: 'zasob', postac: 'tekst', wymagane: true },
    ],
  },
  {
    grupa: 'fotografia',
    komenda: Command.DesignPhotoRetouch,
    nazwa: 'Retuszuj obszary',
    okno: true,
    pola: [
      { kod: 'regions', etykieta: 'Obszary', rodzaj: 'wielowiersz', postac: 'obszary' },
      { kod: 'mode', etykieta: 'Sposób', rodzaj: 'wybor', postac: 'tekst',
        pozycje: [
          { wartosc: '', etykieta: 'Leczenie z otoczenia (domyślnie)' },
          { wartosc: 'heal', etykieta: 'Leczenie z otoczenia' },
          { wartosc: 'clone', etykieta: 'Klonowanie ze źródła' },
        ] },
      { kod: 'sourceX', etykieta: 'Źródło klonowania — X', rodzaj: 'liczba', postac: 'liczba', wymagane: true },
      { kod: 'sourceY', etykieta: 'Źródło klonowania — Y', rodzaj: 'liczba', postac: 'liczba', wymagane: true },
      { kod: 'assetId', etykieta: 'Materiał', rodzaj: 'zasob', postac: 'tekst', wymagane: true },
    ],
  },
  {
    grupa: 'fotografia',
    komenda: Command.DesignPhotoInpaint,
    nazwa: 'Domaluj obszar',
    okno: true,
    pola: [
      { kod: 'regions', etykieta: 'Obszary (gdy maski nie ma)', rodzaj: 'wielowiersz', postac: 'obszary' },
      { kod: 'prompt', etykieta: 'Opis treści', rodzaj: 'tekst', postac: 'tekst' },
      { kod: 'assetId', etykieta: 'Materiał', rodzaj: 'zasob', postac: 'tekst', wymagane: true },
      { kod: 'maskAssetId', etykieta: 'Maska', rodzaj: 'zasob', postac: 'tekst', wymagane: true },
      { kod: 'channelId', etykieta: 'Kanał modelu obrazowego', rodzaj: 'tekst', postac: 'tekst' },
    ],
  },
  {
    grupa: 'fotografia',
    komenda: Command.DesignPhotoExpand,
    nazwa: 'Rozszerz kadr',
    okno: true,
    pola: [
      { kod: 'left', etykieta: 'Z lewej (px)', rodzaj: 'liczba', postac: 'liczba' },
      { kod: 'right', etykieta: 'Z prawej (px)', rodzaj: 'liczba', postac: 'liczba' },
      { kod: 'top', etykieta: 'Od góry (px)', rodzaj: 'liczba', postac: 'liczba' },
      { kod: 'bottom', etykieta: 'Od dołu (px)', rodzaj: 'liczba', postac: 'liczba' },
      { kod: 'prompt', etykieta: 'Opis treści nowego obszaru', rodzaj: 'tekst', postac: 'tekst' },
      { kod: 'assetId', etykieta: 'Materiał', rodzaj: 'zasob', postac: 'tekst', wymagane: true },
      { kod: 'channelId', etykieta: 'Kanał modelu obrazowego', rodzaj: 'tekst', postac: 'tekst' },
    ],
  },
  {
    grupa: 'fotografia',
    komenda: Command.DesignPhotoBackgroundRemove,
    nazwa: 'Odetnij tło',
    okno: true,
    pola: [
      { kod: 'tolerance', etykieta: 'Tolerancja (0–1)', rodzaj: 'liczba', postac: 'liczba' },
      { kod: 'assetId', etykieta: 'Materiał', rodzaj: 'zasob', postac: 'tekst', wymagane: true },
      { kod: 'channelId', etykieta: 'Kanał modelu obrazowego', rodzaj: 'tekst', postac: 'tekst' },
    ],
  },
  {
    grupa: 'fotografia',
    komenda: Command.DesignPhotoSelectObject,
    nazwa: 'Zaznacz obiekt',
    okno: true,
    pola: [
      { kod: 'pointX', etykieta: 'Punkt wewnątrz obiektu — X', rodzaj: 'liczba', postac: 'liczba', wymagane: true },
      { kod: 'pointY', etykieta: 'Punkt wewnątrz obiektu — Y', rodzaj: 'liczba', postac: 'liczba', wymagane: true },
      { kod: 'tolerance', etykieta: 'Tolerancja (0–1)', rodzaj: 'liczba', postac: 'liczba' },
      { kod: 'assetId', etykieta: 'Materiał', rodzaj: 'zasob', postac: 'tekst', wymagane: true },
    ],
  },
  {
    grupa: 'fotografia',
    komenda: Command.DesignPhotoMaskSet,
    nazwa: 'Nałóż maskę',
    okno: true,
    pola: [
      { kod: 'invert', etykieta: 'Odwróć maskę', rodzaj: 'logiczne', postac: 'logiczne' },
      { kod: 'featherPx', etykieta: 'Miękkość krawędzi (px)', rodzaj: 'liczba', postac: 'liczba' },
      { kod: 'assetId', etykieta: 'Materiał', rodzaj: 'zasob', postac: 'tekst', wymagane: true },
      { kod: 'maskAssetId', etykieta: 'Maska', rodzaj: 'zasob', postac: 'tekst', wymagane: true },
    ],
  },
  {
    grupa: 'fotografia',
    komenda: Command.DesignPhotoVectorize,
    nazwa: 'Obrysuj kontury',
    okno: true,
    pola: [
      { kod: 'colors', etykieta: 'Liczba barw (2–64)', rodzaj: 'liczba', postac: 'liczba' },
      { kod: 'threshold', etykieta: 'Próg (0–1)', rodzaj: 'liczba', postac: 'liczba' },
      { kod: 'smoothing', etykieta: 'Wygładzenie (px)', rodzaj: 'liczba', postac: 'liczba' },
      { kod: 'assetId', etykieta: 'Materiał', rodzaj: 'zasob', postac: 'tekst', wymagane: true },
    ],
  },
  {
    grupa: 'fotografia',
    komenda: Command.DesignPhotoBatchApply,
    nazwa: 'Puść wsad',
    okno: true,
    pola: [
      { kod: 'assetIds', etykieta: 'Materiały', rodzaj: 'zasoby', postac: 'lista' },
      { kod: 'presetId', etykieta: 'Nastawa', rodzaj: 'tekst', postac: 'tekst' },
      { kod: 'operations', etykieta: 'Czynności (gdy nastawy nie ma)', rodzaj: 'wielowiersz', postac: 'json' },
    ],
  },
  {
    grupa: 'fotografia',
    komenda: Command.DesignPhotoLayerComposite,
    nazwa: 'Złóż warstwy',
    okno: true,
    pola: [
      { kod: 'layers', etykieta: 'Warstwy', rodzaj: 'wielowiersz', postac: 'json', wymagane: true },
      { kod: 'width', etykieta: 'Szerokość płótna (px)', rodzaj: 'liczba', postac: 'liczba' },
      { kod: 'height', etykieta: 'Wysokość płótna (px)', rodzaj: 'liczba', postac: 'liczba' },
    ],
  },
  {
    grupa: 'fotografia',
    komenda: Command.DesignPhotoPresetSave,
    nazwa: 'Zapisz nastawę',
    okno: true,
    pola: [
      { kod: 'name', etykieta: 'Nazwa nastawy', rodzaj: 'tekst', postac: 'tekst', wymagane: true },
      { kod: 'operations', etykieta: 'Czynności', rodzaj: 'wielowiersz', postac: 'json', wymagane: true },
      { kod: 'presetId', etykieta: 'Nastawa nadpisywana', rodzaj: 'tekst', postac: 'tekst' },
    ],
  },
  {
    grupa: 'fotografia',
    komenda: Command.DesignPhotoPresetList,
    nazwa: 'Wykaz nastaw',
    okno: true,
    pola: [],
  },
  {
    grupa: 'fotografia',
    komenda: Command.DesignPhotoMetadataGet,
    nazwa: 'Zmierz właściwości',
    okno: false,
    pola: [
      { kod: 'assetId', etykieta: 'Materiał', rodzaj: 'zasob', postac: 'tekst', wymagane: true },
    ],
  },
  {
    grupa: 'fotografia',
    komenda: Command.DesignPhotoHistoryGet,
    nazwa: 'Łańcuch edycji',
    okno: false,
    pola: [
      { kod: 'limit', etykieta: 'Granica liczby ogniw', rodzaj: 'liczba', postac: 'liczba' },
      { kod: 'assetId', etykieta: 'Materiał', rodzaj: 'zasob', postac: 'tekst', wymagane: true },
    ],
  },
  {
    grupa: 'wektor',
    komenda: Command.DesignVectorPathSet,
    nazwa: 'Narysuj ścieżkę',
    okno: false,
    pola: [
      { kod: 'boardId', etykieta: 'Kompozycja', rodzaj: 'tekst', postac: 'tekst', wymagane: true },
      { kod: 'nodes', etykieta: 'Węzły', rodzaj: 'wielowiersz', postac: 'json', wymagane: true },
      { kod: 'pathId', etykieta: 'Ścieżka zmieniana', rodzaj: 'tekst', postac: 'tekst' },
      { kod: 'layerId', etykieta: 'Warstwa', rodzaj: 'tekst', postac: 'tekst' },
      { kod: 'closed', etykieta: 'Zamknięta', rodzaj: 'logiczne', postac: 'logiczne' },
      { kod: 'name', etykieta: 'Nazwa ścieżki', rodzaj: 'tekst', postac: 'tekst' },
    ],
  },
  {
    grupa: 'wektor',
    komenda: Command.DesignVectorPathList,
    nazwa: 'Wykaz ścieżek',
    okno: false,
    pola: [
      { kod: 'boardId', etykieta: 'Kompozycja', rodzaj: 'tekst', postac: 'tekst', wymagane: true },
      { kod: 'layerId', etykieta: 'Zawężenie do warstwy', rodzaj: 'tekst', postac: 'tekst' },
    ],
  },
  {
    grupa: 'wektor',
    komenda: Command.DesignVectorPathRemove,
    nazwa: 'Usuń ścieżkę',
    okno: false,
    pola: [
      { kod: 'pathId', etykieta: 'Ścieżka', rodzaj: 'tekst', postac: 'tekst', wymagane: true },
    ],
  },
  {
    grupa: 'wektor',
    komenda: Command.DesignVectorShapeAdd,
    nazwa: 'Dołóż kształt',
    okno: false,
    pola: [
      { kod: 'boardId', etykieta: 'Kompozycja', rodzaj: 'tekst', postac: 'tekst', wymagane: true },
      { kod: 'kind', etykieta: 'Kształt', rodzaj: 'wybor', postac: 'tekst', wymagane: true,
        pozycje: [
          { wartosc: 'rectangle', etykieta: 'Prostokąt' },
          { wartosc: 'ellipse', etykieta: 'Elipsa' },
          { wartosc: 'polygon', etykieta: 'Wielokąt' },
          { wartosc: 'star', etykieta: 'Gwiazda' },
          { wartosc: 'line', etykieta: 'Odcinek' },
        ] },
      { kod: 'x', etykieta: 'X', rodzaj: 'liczba', postac: 'liczba', wymagane: true },
      { kod: 'y', etykieta: 'Y', rodzaj: 'liczba', postac: 'liczba', wymagane: true },
      { kod: 'width', etykieta: 'Szerokość', rodzaj: 'liczba', postac: 'liczba', wymagane: true },
      { kod: 'height', etykieta: 'Wysokość', rodzaj: 'liczba', postac: 'liczba', wymagane: true },
      { kod: 'cornerRadius', etykieta: 'Zaokrąglenie naroży', rodzaj: 'liczba', postac: 'liczba' },
      { kod: 'points', etykieta: 'Wierzchołki / ramiona', rodzaj: 'liczba', postac: 'liczba' },
      { kod: 'innerRadius', etykieta: 'Promień wewnętrzny gwiazdy', rodzaj: 'liczba', postac: 'liczba' },
      { kod: 'layerId', etykieta: 'Warstwa', rodzaj: 'tekst', postac: 'tekst' },
    ],
  },
  {
    grupa: 'wektor',
    komenda: Command.DesignVectorBoolean,
    nazwa: 'Operacja logiczna',
    okno: false,
    pola: [
      { kod: 'pathIds', etykieta: 'Ścieżki', rodzaj: 'tekst', postac: 'lista' },
      { kod: 'operation', etykieta: 'Operacja', rodzaj: 'wybor', postac: 'tekst', wymagane: true,
        pozycje: [
          { wartosc: 'union', etykieta: 'Suma' },
          { wartosc: 'subtract', etykieta: 'Różnica' },
          { wartosc: 'intersect', etykieta: 'Część wspólna' },
          { wartosc: 'exclude', etykieta: 'Wykluczenie' },
        ] },
      { kod: 'keepSources', etykieta: 'Zostaw ścieżki źródłowe', rodzaj: 'logiczne', postac: 'logiczne' },
    ],
  },
  {
    grupa: 'wektor',
    komenda: Command.DesignVectorTextPath,
    nazwa: 'Tekst na ścieżce',
    okno: false,
    pola: [
      { kod: 'boardId', etykieta: 'Kompozycja', rodzaj: 'tekst', postac: 'tekst', wymagane: true },
      { kod: 'text', etykieta: 'Treść', rodzaj: 'tekst', postac: 'tekst', wymagane: true },
      { kod: 'fontFamily', etykieta: 'Krój pisma', rodzaj: 'tekst', postac: 'tekst', wymagane: true },
      { kod: 'fontSize', etykieta: 'Rozmiar pisma', rodzaj: 'liczba', postac: 'liczba', wymagane: true },
      { kod: 'pathId', etykieta: 'Ścieżka nośna', rodzaj: 'tekst', postac: 'tekst' },
      { kod: 'outline', etykieta: 'Zamień w kontury', rodzaj: 'logiczne', postac: 'logiczne' },
      { kod: 'x', etykieta: 'X (bez ścieżki)', rodzaj: 'liczba', postac: 'liczba' },
      { kod: 'y', etykieta: 'Y (bez ścieżki)', rodzaj: 'liczba', postac: 'liczba' },
    ],
  },
  {
    grupa: 'wektor',
    komenda: Command.DesignVectorOptimize,
    nazwa: 'Oczyść zapis',
    okno: false,
    pola: [
      { kod: 'pathIds', etykieta: 'Ścieżki', rodzaj: 'tekst', postac: 'lista' },
      { kod: 'boardId', etykieta: 'Kompozycja (gdy ścieżek nie wskazano)', rodzaj: 'tekst', postac: 'tekst', wymagane: true },
      { kod: 'precision', etykieta: 'Miejsca po przecinku', rodzaj: 'liczba', postac: 'liczba' },
    ],
  },
  {
    grupa: 'wektor',
    komenda: Command.DesignVectorSymbolSet,
    nazwa: 'Zapisz symbol',
    okno: false,
    pola: [
      { kod: 'boardId', etykieta: 'Kompozycja', rodzaj: 'tekst', postac: 'tekst', wymagane: true },
      { kod: 'name', etykieta: 'Nazwa symbolu', rodzaj: 'tekst', postac: 'tekst', wymagane: true },
      { kod: 'symbolId', etykieta: 'Symbol zmieniany', rodzaj: 'tekst', postac: 'tekst' },
      { kod: 'pathIds', etykieta: 'Ścieżki', rodzaj: 'tekst', postac: 'lista' },
      { kod: 'layerIds', etykieta: 'Warstwy', rodzaj: 'tekst', postac: 'lista' },
    ],
  },
  {
    grupa: 'wektor',
    komenda: Command.DesignVectorSymbolList,
    nazwa: 'Wykaz symboli',
    okno: false,
    pola: [
      { kod: 'boardId', etykieta: 'Kompozycja', rodzaj: 'tekst', postac: 'tekst', wymagane: true },
    ],
  },
  {
    grupa: 'wektor',
    komenda: Command.DesignVectorExport,
    nazwa: 'Wydaj wektor',
    okno: false,
    pola: [
      { kod: 'boardId', etykieta: 'Kompozycja', rodzaj: 'tekst', postac: 'tekst', wymagane: true },
      { kod: 'target', etykieta: 'Postać', rodzaj: 'wybor', postac: 'tekst', wymagane: true,
        pozycje: [
          { wartosc: 'svg', etykieta: 'SVG' },
          { wartosc: 'pdf', etykieta: 'PDF' },
          { wartosc: 'eps', etykieta: 'EPS' },
        ] },
      { kod: 'pathIds', etykieta: 'Ścieżki (brak bierze całość)', rodzaj: 'tekst', postac: 'lista' },
      { kod: 'frameId', etykieta: 'Ramka zawężająca', rodzaj: 'tekst', postac: 'tekst' },
    ],
  },
  {
    grupa: 'druk',
    komenda: Command.DesignPrintProfileSet,
    nazwa: 'Zapisz profil wydania',
    okno: true,
    pola: [
      { kod: 'colorSpace', etykieta: 'Przestrzeń barw', rodzaj: 'wybor', postac: 'tekst', wymagane: true, gniazdo: 'profile',
        pozycje: [
          { wartosc: 'cmyk', etykieta: 'CMYK' },
          { wartosc: 'rgb', etykieta: 'RGB' },
          { wartosc: 'grayscale', etykieta: 'Skala szarości' },
          { wartosc: 'spot', etykieta: 'Barwy dodatkowe' },
        ] },
      { kod: 'name', etykieta: 'Nazwa profilu', rodzaj: 'tekst', postac: 'tekst', gniazdo: 'profile' },
      { kod: 'standard', etykieta: 'Norma', rodzaj: 'wybor', postac: 'tekst', gniazdo: 'profile',
        pozycje: [
          { wartosc: '', etykieta: 'bez normy' },
          { wartosc: 'pdfX1a', etykieta: 'PDF/X-1a' },
          { wartosc: 'pdfX3', etykieta: 'PDF/X-3' },
          { wartosc: 'pdfX4', etykieta: 'PDF/X-4' },
          { wartosc: 'pdfA2b', etykieta: 'PDF/A-2b' },
        ] },
      { kod: 'bleedMm', etykieta: 'Spad (mm)', rodzaj: 'liczba', postac: 'liczba', gniazdo: 'profile' },
      { kod: 'cropMarks', etykieta: 'Znaczniki cięcia', rodzaj: 'logiczne', postac: 'logiczne', gniazdo: 'profile' },
      { kod: 'registrationMarks', etykieta: 'Znaczniki pasowania', rodzaj: 'logiczne', postac: 'logiczne', gniazdo: 'profile' },
      { kod: 'colorBar', etykieta: 'Pasek kontrolny barw', rodzaj: 'logiczne', postac: 'logiczne', gniazdo: 'profile' },
      { kod: 'dpi', etykieta: 'Rozdzielczość (dpi)', rodzaj: 'liczba', postac: 'liczba', gniazdo: 'profile' },
      { kod: 'iccProfile', etykieta: 'Profil ICC', rodzaj: 'tekst', postac: 'tekst', gniazdo: 'profile' },
      { kod: 'overprintBlack', etykieta: 'Nadruk czerni', rodzaj: 'logiczne', postac: 'logiczne', gniazdo: 'profile' },
      { kod: 'paperSize', etykieta: 'Nośnik', rodzaj: 'tekst', postac: 'tekst', gniazdo: 'profile' },
      { kod: 'profileId', etykieta: 'Profil nadpisywany', rodzaj: 'tekst', postac: 'tekst' },
    ],
  },
  {
    grupa: 'druk',
    komenda: Command.DesignPrintProfileList,
    nazwa: 'Wykaz profili',
    okno: true,
    pola: [],
  },
  {
    grupa: 'druk',
    komenda: Command.DesignPrintPaperList,
    nazwa: 'Wykaz nośników',
    okno: false,
    pola: [
      { kod: 'family', etykieta: 'Rodzina', rodzaj: 'tekst', postac: 'tekst' },
    ],
  },
  {
    grupa: 'druk',
    komenda: Command.DesignPrintPreflight,
    nazwa: 'Kontrola przeddrukowa',
    okno: false,
    pola: [
      { kod: 'boardId', etykieta: 'Kompozycja', rodzaj: 'tekst', postac: 'tekst', wymagane: true },
      { kod: 'assetId', etykieta: 'Zasób', rodzaj: 'zasob', postac: 'tekst', wymagane: true },
      { kod: 'profileId', etykieta: 'Profil', rodzaj: 'tekst', postac: 'tekst' },
    ],
  },
  {
    grupa: 'druk',
    komenda: Command.DesignPrintExport,
    nazwa: 'Wydaj do druku',
    okno: true,
    pola: [
      { kod: 'format', etykieta: 'Format', rodzaj: 'wybor', postac: 'tekst', wymagane: true,
        pozycje: [
          { wartosc: 'pdf', etykieta: 'PDF' },
          { wartosc: 'tiff', etykieta: 'TIFF' },
          { wartosc: 'eps', etykieta: 'EPS' },
        ] },
      { kod: 'boardId', etykieta: 'Kompozycja', rodzaj: 'tekst', postac: 'tekst' },
      { kod: 'assetId', etykieta: 'Zasób', rodzaj: 'zasob', postac: 'tekst' },
      { kod: 'frameId', etykieta: 'Ramka zawężająca', rodzaj: 'tekst', postac: 'tekst' },
      { kod: 'profileId', etykieta: 'Profil', rodzaj: 'tekst', postac: 'tekst' },
      { kod: 'skipPreflight', etykieta: 'Pomiń kontrolę przeddrukową', rodzaj: 'logiczne', postac: 'logiczne' },
    ],
  },
  {
    grupa: 'druk',
    komenda: Command.DesignLargeformatTile,
    nazwa: 'Podziel na kafle',
    okno: true,
    pola: [
      { kod: 'tileWidthMm', etykieta: 'Szerokość kafla (mm)', rodzaj: 'liczba', postac: 'liczba', wymagane: true },
      { kod: 'tileHeightMm', etykieta: 'Wysokość kafla (mm)', rodzaj: 'liczba', postac: 'liczba', wymagane: true },
      { kod: 'overlapMm', etykieta: 'Zakładka (mm)', rodzaj: 'liczba', postac: 'liczba' },
      { kod: 'targetWidthMm', etykieta: 'Szerokość całości (mm)', rodzaj: 'liczba', postac: 'liczba' },
      { kod: 'targetHeightMm', etykieta: 'Wysokość całości (mm)', rodzaj: 'liczba', postac: 'liczba' },
      { kod: 'markers', etykieta: 'Znaczniki sklejenia', rodzaj: 'logiczne', postac: 'logiczne' },
      { kod: 'assetId', etykieta: 'Materiał', rodzaj: 'zasob', postac: 'tekst', wymagane: true },
    ],
  },
  {
    grupa: 'druk',
    komenda: Command.DesignChartRender,
    nazwa: 'Wyrysuj wykres',
    okno: true,
    pola: [
      { kod: 'kind', etykieta: 'Rodzaj', rodzaj: 'wybor', postac: 'tekst', wymagane: true,
        pozycje: [
          { wartosc: 'rectangle', etykieta: 'Prostokąt' },
          { wartosc: 'ellipse', etykieta: 'Elipsa' },
          { wartosc: 'polygon', etykieta: 'Wielokąt' },
          { wartosc: 'star', etykieta: 'Gwiazda' },
          { wartosc: 'line', etykieta: 'Odcinek' },
        ] },
      { kod: 'series', etykieta: 'Serie danych', rodzaj: 'wielowiersz', postac: 'json', wymagane: true },
      { kod: 'categories', etykieta: 'Podpisy kategorii', rodzaj: 'tekst', postac: 'lista' },
      { kod: 'title', etykieta: 'Tytuł', rodzaj: 'tekst', postac: 'tekst' },
      { kod: 'width', etykieta: 'Szerokość', rodzaj: 'liczba', postac: 'liczba' },
      { kod: 'height', etykieta: 'Wysokość', rodzaj: 'liczba', postac: 'liczba' },
      { kod: 'format', etykieta: 'Format', rodzaj: 'wybor', postac: 'tekst',
        pozycje: [
          { wartosc: 'pdf', etykieta: 'PDF' },
          { wartosc: 'tiff', etykieta: 'TIFF' },
          { wartosc: 'eps', etykieta: 'EPS' },
        ] },
      { kod: 'tokenSetId', etykieta: 'Zestaw żetonów', rodzaj: 'tekst', postac: 'tekst' },
      { kod: 'legend', etykieta: 'Legenda', rodzaj: 'logiczne', postac: 'logiczne' },
    ],
  },
  {
    grupa: 'druk',
    komenda: Command.DesignDiagramRender,
    nazwa: 'Wyrysuj schemat',
    okno: true,
    pola: [
      { kod: 'kind', etykieta: 'Rodzaj', rodzaj: 'wybor', postac: 'tekst', wymagane: true,
        pozycje: [
          { wartosc: 'rectangle', etykieta: 'Prostokąt' },
          { wartosc: 'ellipse', etykieta: 'Elipsa' },
          { wartosc: 'polygon', etykieta: 'Wielokąt' },
          { wartosc: 'star', etykieta: 'Gwiazda' },
          { wartosc: 'line', etykieta: 'Odcinek' },
        ] },
      { kod: 'nodes', etykieta: 'Węzły', rodzaj: 'wielowiersz', postac: 'json', wymagane: true },
      { kod: 'edges', etykieta: 'Połączenia', rodzaj: 'wielowiersz', postac: 'json', wymagane: true },
      { kod: 'title', etykieta: 'Tytuł', rodzaj: 'tekst', postac: 'tekst' },
      { kod: 'direction', etykieta: 'Kierunek', rodzaj: 'wybor', postac: 'tekst',
        pozycje: [
          { wartosc: '', etykieta: 'pionowo (domyślnie)' },
          { wartosc: 'vertical', etykieta: 'Pionowo' },
          { wartosc: 'horizontal', etykieta: 'Poziomo' },
        ] },
      { kod: 'format', etykieta: 'Format', rodzaj: 'wybor', postac: 'tekst',
        pozycje: [
          { wartosc: 'pdf', etykieta: 'PDF' },
          { wartosc: 'tiff', etykieta: 'TIFF' },
          { wartosc: 'eps', etykieta: 'EPS' },
        ] },
      { kod: 'tokenSetId', etykieta: 'Zestaw żetonów', rodzaj: 'tekst', postac: 'tekst' },
    ],
  },
  {
    grupa: 'bazy',
    komenda: Command.DesignStockSearch,
    nazwa: 'Szukaj w bazach',
    okno: true,
    pola: [
      { kod: 'query', etykieta: 'Fraza', rodzaj: 'tekst', postac: 'tekst', wymagane: true },
      { kod: 'provider', etykieta: 'Dostawca', rodzaj: 'wybor', postac: 'tekst',
        pozycje: [
          { wartosc: '', etykieta: 'wszyscy' },
          { wartosc: 'openverse', etykieta: 'Openverse (bez klucza)' },
          { wartosc: 'wikimedia', etykieta: 'Wikimedia Commons (bez klucza)' },
          { wartosc: 'met', etykieta: 'Met Museum (bez klucza)' },
          { wartosc: 'nasa', etykieta: 'NASA (bez klucza)' },
          { wartosc: 'unsplash', etykieta: 'Unsplash (klucz z sejfu)' },
          { wartosc: 'pexels', etykieta: 'Pexels (klucz z sejfu)' },
          { wartosc: 'pixabay', etykieta: 'Pixabay (klucz z sejfu)' },
          { wartosc: 'smithsonian', etykieta: 'Smithsonian (klucz z sejfu)' },
        ] },
      { kod: 'limit', etykieta: 'Granica na dostawcę', rodzaj: 'liczba', postac: 'liczba' },
    ],
  },
  {
    grupa: 'bazy',
    komenda: Command.DesignStockImport,
    nazwa: 'Wciągnij zasób',
    okno: true,
    pola: [
      { kod: 'provider', etykieta: 'Dostawca', rodzaj: 'tekst', postac: 'tekst', wymagane: true },
      { kod: 'externalId', etykieta: 'Identyfikator u dostawcy', rodzaj: 'tekst', postac: 'tekst', wymagane: true },
    ],
  },
  {
    grupa: 'publikacja',
    komenda: Command.DesignTemplateSave,
    nazwa: 'Zapisz szablon albo publikację',
    okno: true,
    pola: [
      { kod: 'name', etykieta: 'Nazwa', rodzaj: 'tekst', postac: 'tekst', wymagane: true },
      { kod: 'kind', etykieta: 'Rodzaj materiału', rodzaj: 'wybor', postac: 'tekst', wymagane: true,
        pozycje: [
          { wartosc: 'rectangle', etykieta: 'Prostokąt' },
          { wartosc: 'ellipse', etykieta: 'Elipsa' },
          { wartosc: 'polygon', etykieta: 'Wielokąt' },
          { wartosc: 'star', etykieta: 'Gwiazda' },
          { wartosc: 'line', etykieta: 'Odcinek' },
        ] },
      { kod: 'width', etykieta: 'Szerokość', rodzaj: 'liczba', postac: 'liczba', wymagane: true },
      { kod: 'height', etykieta: 'Wysokość', rodzaj: 'liczba', postac: 'liczba', wymagane: true },
      { kod: 'description', etykieta: 'Do czego służy', rodzaj: 'tekst', postac: 'tekst' },
      { kod: 'templateId', etykieta: 'Szablon nadpisywany', rodzaj: 'tekst', postac: 'tekst' },
      { kod: 'pages', etykieta: 'Strony publikacji', rodzaj: 'wielowiersz', postac: 'json' },
    ],
  },
  {
    grupa: 'publikacja',
    komenda: Command.DesignTemplateList,
    nazwa: 'Wykaz szablonów',
    okno: true,
    pola: [
      { kod: 'kind', etykieta: 'Rodzaj', rodzaj: 'wybor', postac: 'tekst',
        pozycje: [
          { wartosc: 'rectangle', etykieta: 'Prostokąt' },
          { wartosc: 'ellipse', etykieta: 'Elipsa' },
          { wartosc: 'polygon', etykieta: 'Wielokąt' },
          { wartosc: 'star', etykieta: 'Gwiazda' },
          { wartosc: 'line', etykieta: 'Odcinek' },
        ] },
    ],
  },
  {
    grupa: 'publikacja',
    komenda: Command.DesignTemplateApply,
    nazwa: 'Zastosuj szablon',
    okno: true,
    pola: [
      { kod: 'templateId', etykieta: 'Szablon', rodzaj: 'tekst', postac: 'tekst', wymagane: true },
      { kod: 'boardId', etykieta: 'Kompozycja docelowa', rodzaj: 'tekst', postac: 'tekst' },
      { kod: 'pageNumber', etykieta: 'Strona publikacji', rodzaj: 'liczba', postac: 'liczba' },
      { kod: 'replacements', etykieta: 'Podstawienia treści', rodzaj: 'wielowiersz', postac: 'json' },
    ],
  },
  {
    grupa: 'publikacja',
    komenda: Command.DesignPrintExport,
    nazwa: 'Wydaj publikację',
    okno: true,
    pola: [
      { kod: 'templateId', etykieta: 'Szablon publikacji', rodzaj: 'tekst', postac: 'tekst', wymagane: true },
      { kod: 'format', etykieta: 'Format', rodzaj: 'wybor', postac: 'tekst', wymagane: true,
        pozycje: [
          { wartosc: 'pdf', etykieta: 'PDF' },
          { wartosc: 'tiff', etykieta: 'TIFF' },
          { wartosc: 'eps', etykieta: 'EPS' },
        ] },
      { kod: 'pageOrder', etykieta: 'Kolejność stron', rodzaj: 'tekst', postac: 'listaLiczb' },
      { kod: 'binding', etykieta: 'Oprawa', rodzaj: 'wybor', postac: 'tekst',
        pozycje: [
          { wartosc: '', etykieta: 'bez oprawy' },
          { wartosc: 'brak', etykieta: 'Bez oprawy' },
          { wartosc: 'zeszytowa', etykieta: 'Zeszytowa (stron ÷ 4)' },
          { wartosc: 'klejona', etykieta: 'Klejona' },
          { wartosc: 'spiralna', etykieta: 'Spiralna' },
        ] },
      { kod: 'profileId', etykieta: 'Profil wydania', rodzaj: 'tekst', postac: 'tekst' },
      { kod: 'skipPreflight', etykieta: 'Pomiń kontrolę przeddrukową', rodzaj: 'logiczne', postac: 'logiczne' },
    ],
  },
  {
    grupa: 'publikacja',
    komenda: Command.DesignCampaignSetBuild,
    nazwa: 'Zbuduj komplet kampanii',
    okno: true,
    pola: [
      { kod: 'boardId', etykieta: 'Kompozycja źródłowa', rodzaj: 'tekst', postac: 'tekst', wymagane: true },
      { kod: 'sizes', etykieta: 'Rozmiary', rodzaj: 'wielowiersz', postac: 'json', wymagane: true },
      { kod: 'format', etykieta: 'Format', rodzaj: 'wybor', postac: 'tekst',
        pozycje: [
          { wartosc: 'pdf', etykieta: 'PDF' },
          { wartosc: 'tiff', etykieta: 'TIFF' },
          { wartosc: 'eps', etykieta: 'EPS' },
        ] },
    ],
  },
  {
    grupa: 'fotografia',
    komenda: Command.DesignColorPaletteGenerate,
    nazwa: 'Zbuduj paletę z harmonii',
    okno: true,
    pola: [
      { kod: 'baseColor', etykieta: 'Barwa wiodąca', rodzaj: 'tekst', postac: 'tekst', wymagane: true },
      { kod: 'harmony', etykieta: 'Harmonia', rodzaj: 'wybor', postac: 'tekst', wymagane: true,
        pozycje: [
          { wartosc: 'complementary', etykieta: 'Dopełnienie' },
          { wartosc: 'analogous', etykieta: 'Analogia' },
          { wartosc: 'triad', etykieta: 'Triada' },
          { wartosc: 'tetrad', etykieta: 'Tetrada' },
          { wartosc: 'splitComplementary', etykieta: 'Dopełnienie rozdzielone' },
          { wartosc: 'mono', etykieta: 'Monochrom' },
        ] },
      { kod: 'count', etykieta: 'Liczba barw', rodzaj: 'liczba', postac: 'liczba' },
    ],
  },
  {
    grupa: 'fotografia',
    komenda: Command.DesignColorPaletteExtract,
    nazwa: 'Wyciągnij paletę z obrazu',
    okno: false,
    pola: [
      { kod: 'count', etykieta: 'Liczba barw', rodzaj: 'liczba', postac: 'liczba' },
      { kod: 'assetId', etykieta: 'Materiał', rodzaj: 'zasob', postac: 'tekst', wymagane: true },
    ],
  },
  {
    grupa: 'fotografia',
    komenda: Command.DesignColorContrastCheck,
    nazwa: 'Zmierz kontrast',
    okno: false,
    pola: [
      { kod: 'foreground', etykieta: 'Barwa pierwszoplanowa', rodzaj: 'tekst', postac: 'tekst', wymagane: true },
      { kod: 'background', etykieta: 'Barwa tła', rodzaj: 'tekst', postac: 'tekst', wymagane: true },
      { kod: 'fontSize', etykieta: 'Rozmiar pisma', rodzaj: 'liczba', postac: 'liczba' },
      { kod: 'bold', etykieta: 'Pismo pogrubione', rodzaj: 'logiczne', postac: 'logiczne' },
    ],
  },
  {
    grupa: 'fotografia',
    komenda: Command.DesignColorVisionSimulate,
    nazwa: 'Symuluj wadę widzenia',
    okno: true,
    pola: [
      { kod: 'vision', etykieta: 'Wada widzenia', rodzaj: 'wybor', postac: 'tekst', wymagane: true,
        pozycje: [
          { wartosc: 'protanopia', etykieta: 'Protanopia' },
          { wartosc: 'deuteranopia', etykieta: 'Deuteranopia' },
          { wartosc: 'tritanopia', etykieta: 'Tritanopia' },
          { wartosc: 'achromatopsia', etykieta: 'Achromatopsja' },
        ] },
      { kod: 'assetId', etykieta: 'Materiał', rodzaj: 'zasob', postac: 'tekst', wymagane: true },
    ],
  },
  {
    grupa: 'fotografia',
    komenda: Command.DesignColorConvert,
    nazwa: 'Przelicz barwę',
    okno: false,
    pola: [
      { kod: 'value', etykieta: 'Zapis barwy', rodzaj: 'tekst', postac: 'tekst', wymagane: true },
      { kod: 'space', etykieta: 'Przestrzeń wejściowa', rodzaj: 'wybor', postac: 'tekst',
        pozycje: [
          { wartosc: '', etykieta: 'rozpoznaj sam' },
          { wartosc: 'hex', etykieta: 'Szesnastkowo' },
          { wartosc: 'rgb', etykieta: 'RGB' },
          { wartosc: 'hsl', etykieta: 'HSL' },
          { wartosc: 'lab', etykieta: 'Lab' },
          { wartosc: 'cmyk', etykieta: 'CMYK' },
        ] },
    ],
  },
  {
    grupa: 'fotografia',
    komenda: Command.DesignColorAccessibilityAudit,
    nazwa: 'Zbadaj dostępność zestawu',
    okno: false,
    pola: [
      { kod: 'tokenSetId', etykieta: 'Zestaw żetonów', rodzaj: 'tekst', postac: 'tekst', wymagane: true },
      { kod: 'minimumRatio', etykieta: 'Próg kontrastu', rodzaj: 'liczba', postac: 'liczba' },
    ],
  },
  {
    grupa: 'wektor',
    komenda: Command.DesignColorGradientSet,
    nazwa: 'Ustaw gradient',
    okno: false,
    pola: [
      { kod: 'boardId', etykieta: 'Kompozycja', rodzaj: 'tekst', postac: 'tekst', wymagane: true },
      { kod: 'gradient', etykieta: 'Gradient', rodzaj: 'wielowiersz', postac: 'json', wymagane: true },
      { kod: 'pathId', etykieta: 'Ścieżka', rodzaj: 'tekst', postac: 'tekst' },
      { kod: 'layerId', etykieta: 'Warstwa', rodzaj: 'tekst', postac: 'tekst' },
    ],
  },
  {
    grupa: 'wektor',
    komenda: Command.DesignIconLibrarySearch,
    nazwa: 'Szukaj ikony',
    okno: false,
    pola: [
      { kod: 'query', etykieta: 'Fraza', rodzaj: 'tekst', postac: 'tekst' },
      { kod: 'set', etykieta: 'Zestaw', rodzaj: 'tekst', postac: 'tekst' },
      { kod: 'limit', etykieta: 'Granica', rodzaj: 'liczba', postac: 'liczba' },
    ],
  },
  {
    grupa: 'wektor',
    komenda: Command.DesignIconSet,
    nazwa: 'Zapisz ikonę własną',
    okno: true,
    pola: [
      { kod: 'name', etykieta: 'Nazwa', rodzaj: 'tekst', postac: 'tekst', wymagane: true },
      { kod: 'svg', etykieta: 'Treść SVG', rodzaj: 'wielowiersz', postac: 'tekst', wymagane: true },
      { kod: 'iconId', etykieta: 'Ikona zmieniana', rodzaj: 'tekst', postac: 'tekst' },
      { kod: 'gridSize', etykieta: 'Siatka', rodzaj: 'liczba', postac: 'liczba' },
      { kod: 'strokeWidth', etykieta: 'Grubość obrysu', rodzaj: 'liczba', postac: 'liczba' },
      { kod: 'tags', etykieta: 'Etykiety', rodzaj: 'tekst', postac: 'lista' },
    ],
  },
  {
    grupa: 'wektor',
    komenda: Command.DesignIconGenerate,
    nazwa: 'Zbuduj ikony dla pojęć',
    okno: true,
    pola: [
      { kod: 'concepts', etykieta: 'Pojęcia', rodzaj: 'tekst', postac: 'lista' },
      { kod: 'gridSize', etykieta: 'Siatka', rodzaj: 'liczba', postac: 'liczba' },
      { kod: 'strokeWidth', etykieta: 'Grubość obrysu', rodzaj: 'liczba', postac: 'liczba' },
      { kod: 'styleReferenceIconId', etykieta: 'Ikona wzorcowa', rodzaj: 'tekst', postac: 'tekst' },
      { kod: 'channelId', etykieta: 'Kanał modelu obrazowego', rodzaj: 'tekst', postac: 'tekst' },
    ],
  },
  {
    grupa: 'wektor',
    komenda: Command.DesignIconSpriteBuild,
    nazwa: 'Zbuduj pakiet ikon',
    okno: true,
    pola: [
      { kod: 'iconIds', etykieta: 'Ikony', rodzaj: 'tekst', postac: 'lista' },
      { kod: 'kind', etykieta: 'Postać', rodzaj: 'wybor', postac: 'tekst', wymagane: true,
        pozycje: [
          { wartosc: 'rectangle', etykieta: 'Prostokąt' },
          { wartosc: 'ellipse', etykieta: 'Elipsa' },
          { wartosc: 'polygon', etykieta: 'Wielokąt' },
          { wartosc: 'star', etykieta: 'Gwiazda' },
          { wartosc: 'line', etykieta: 'Odcinek' },
        ] },
      { kod: 'name', etykieta: 'Nazwa pakietu', rodzaj: 'tekst', postac: 'tekst' },
    ],
  },
  {
    grupa: 'wektor',
    komenda: Command.DesignFaviconBuild,
    nazwa: 'Zbuduj ikonę witryny',
    okno: true,
    pola: [
      { kod: 'sizes', etykieta: 'Rozmiary', rodzaj: 'tekst', postac: 'listaLiczb' },
      { kod: 'includeManifest', etykieta: 'Dołóż manifest', rodzaj: 'logiczne', postac: 'logiczne' },
      { kod: 'assetId', etykieta: 'Materiał', rodzaj: 'zasob', postac: 'tekst', wymagane: true },
    ],
  },
  {
    grupa: 'wektor',
    komenda: Command.DesignFontPairSuggest,
    nazwa: 'Zestawienia krojów',
    okno: true,
    pola: [
      { kod: 'mood', etykieta: 'Charakter', rodzaj: 'tekst', postac: 'tekst' },
      { kod: 'baseFont', etykieta: 'Krój, do którego szukamy pary', rodzaj: 'tekst', postac: 'tekst' },
      { kod: 'count', etykieta: 'Liczba propozycji', rodzaj: 'liczba', postac: 'liczba' },
      { kod: 'channelId', etykieta: 'Kanał modelu obrazowego', rodzaj: 'tekst', postac: 'tekst' },
    ],
  },
  {
    grupa: 'wektor',
    komenda: Command.DesignFontPreview,
    nazwa: 'Podgląd kroju',
    okno: false,
    pola: [
      { kod: 'fontFamily', etykieta: 'Krój', rodzaj: 'tekst', postac: 'tekst', wymagane: true },
      { kod: 'sampleText', etykieta: 'Tekst próbny', rodzaj: 'tekst', postac: 'tekst' },
      { kod: 'sizes', etykieta: 'Rozmiary', rodzaj: 'tekst', postac: 'listaLiczb' },
      { kod: 'subsetText', etykieta: 'Podzbiór glifów', rodzaj: 'tekst', postac: 'tekst' },
    ],
  },
  {
    grupa: 'wektor',
    komenda: Command.DesignFontGlyphsGet,
    nazwa: 'Glify kroju',
    okno: false,
    pola: [
      { kod: 'fontFamily', etykieta: 'Krój', rodzaj: 'tekst', postac: 'tekst', wymagane: true },
      { kod: 'from', etykieta: 'Od punktu kodowego', rodzaj: 'liczba', postac: 'liczba' },
      { kod: 'to', etykieta: 'Do punktu kodowego', rodzaj: 'liczba', postac: 'liczba' },
      { kod: 'limit', etykieta: 'Granica', rodzaj: 'liczba', postac: 'liczba' },
    ],
  },
  {
    grupa: 'makieta',
    komenda: Command.DesignFrameSet,
    nazwa: 'Ustaw ramkę',
    okno: false,
    pola: [
      { kod: 'boardId', etykieta: 'Kompozycja', rodzaj: 'tekst', postac: 'tekst', wymagane: true },
      { kod: 'name', etykieta: 'Nazwa ramki', rodzaj: 'tekst', postac: 'tekst', wymagane: true },
      { kod: 'frameId', etykieta: 'Ramka zmieniana', rodzaj: 'tekst', postac: 'tekst' },
      { kod: 'width', etykieta: 'Szerokość', rodzaj: 'liczba', postac: 'liczba' },
      { kod: 'height', etykieta: 'Wysokość', rodzaj: 'liczba', postac: 'liczba' },
      { kod: 'x', etykieta: 'X na kanwie', rodzaj: 'liczba', postac: 'liczba' },
      { kod: 'y', etykieta: 'Y na kanwie', rodzaj: 'liczba', postac: 'liczba' },
      { kod: 'devicePreset', etykieta: 'Nastawa urządzenia', rodzaj: 'tekst', postac: 'tekst' },
    ],
  },
  {
    grupa: 'makieta',
    komenda: Command.DesignFrameList,
    nazwa: 'Wykaz ramek',
    okno: false,
    pola: [
      { kod: 'boardId', etykieta: 'Kompozycja', rodzaj: 'tekst', postac: 'tekst', wymagane: true },
    ],
  },
  {
    grupa: 'makieta',
    komenda: Command.DesignFrameRemove,
    nazwa: 'Usuń ramkę',
    okno: false,
    pola: [
      { kod: 'frameId', etykieta: 'Ramka', rodzaj: 'tekst', postac: 'tekst', wymagane: true },
    ],
  },
  {
    grupa: 'makieta',
    komenda: Command.DesignLayoutAuto,
    nazwa: 'Ułóż automatycznie',
    okno: false,
    pola: [
      { kod: 'frameId', etykieta: 'Ramka', rodzaj: 'tekst', postac: 'tekst', wymagane: true },
      { kod: 'direction', etykieta: 'Kierunek', rodzaj: 'wybor', postac: 'tekst', wymagane: true, gniazdo: 'layout',
        pozycje: [
          { wartosc: '', etykieta: 'pionowo (domyślnie)' },
          { wartosc: 'vertical', etykieta: 'Pionowo' },
          { wartosc: 'horizontal', etykieta: 'Poziomo' },
        ] },
      { kod: 'gap', etykieta: 'Odstęp', rodzaj: 'liczba', postac: 'liczba', gniazdo: 'layout' },
      { kod: 'paddingTop', etykieta: 'Odstęp od góry', rodzaj: 'liczba', postac: 'liczba', gniazdo: 'layout' },
      { kod: 'paddingRight', etykieta: 'Odstęp od prawej', rodzaj: 'liczba', postac: 'liczba', gniazdo: 'layout' },
      { kod: 'paddingBottom', etykieta: 'Odstęp od dołu', rodzaj: 'liczba', postac: 'liczba', gniazdo: 'layout' },
      { kod: 'paddingLeft', etykieta: 'Odstęp od lewej', rodzaj: 'liczba', postac: 'liczba', gniazdo: 'layout' },
      { kod: 'align', etykieta: 'Wyrównanie w poprzek', rodzaj: 'wybor', postac: 'tekst', gniazdo: 'layout',
        pozycje: [
          { wartosc: '', etykieta: 'do początku' },
          { wartosc: 'start', etykieta: 'Do początku' },
          { wartosc: 'center', etykieta: 'Do środka' },
          { wartosc: 'end', etykieta: 'Do końca' },
          { wartosc: 'stretch', etykieta: 'Rozciągnij' },
        ] },
      { kod: 'layerIds', etykieta: 'Warstwy w kolejności', rodzaj: 'tekst', postac: 'lista' },
    ],
  },
  {
    grupa: 'makieta',
    komenda: Command.DesignConstraintSet,
    nazwa: 'Ustaw więzy',
    okno: false,
    pola: [
      { kod: 'frameId', etykieta: 'Ramka', rodzaj: 'tekst', postac: 'tekst', wymagane: true },
      { kod: 'constraints', etykieta: 'Więzy', rodzaj: 'wielowiersz', postac: 'json', wymagane: true },
    ],
  },
  {
    grupa: 'makieta',
    komenda: Command.DesignFrameResizeApply,
    nazwa: 'Zmień rozmiar ramki',
    okno: false,
    pola: [
      { kod: 'frameId', etykieta: 'Ramka', rodzaj: 'tekst', postac: 'tekst', wymagane: true },
      { kod: 'width', etykieta: 'Nowa szerokość', rodzaj: 'liczba', postac: 'liczba', wymagane: true },
      { kod: 'height', etykieta: 'Nowa wysokość', rodzaj: 'liczba', postac: 'liczba', wymagane: true },
    ],
  },
  {
    grupa: 'makieta',
    komenda: Command.DesignGridSet,
    nazwa: 'Ustaw siatkę',
    okno: false,
    pola: [
      { kod: 'columns', etykieta: 'Kolumny', rodzaj: 'liczba', postac: 'liczba', gniazdo: 'grid' },
      { kod: 'gutter', etykieta: 'Rynna', rodzaj: 'liczba', postac: 'liczba', gniazdo: 'grid' },
      { kod: 'margin', etykieta: 'Margines', rodzaj: 'liczba', postac: 'liczba', gniazdo: 'grid' },
      { kod: 'baseline', etykieta: 'Siatka bazowa', rodzaj: 'liczba', postac: 'liczba', gniazdo: 'grid' },
      { kod: 'frameId', etykieta: 'Ramka', rodzaj: 'tekst', postac: 'tekst', wymagane: true },
      { kod: 'boardId', etykieta: 'Kompozycja', rodzaj: 'tekst', postac: 'tekst', wymagane: true },
    ],
  },
  {
    grupa: 'makieta',
    komenda: Command.DesignComponentSave,
    nazwa: 'Zapisz komponent',
    okno: true,
    pola: [
      { kod: 'name', etykieta: 'Nazwa', rodzaj: 'tekst', postac: 'tekst', wymagane: true },
      { kod: 'componentId', etykieta: 'Komponent nadpisywany', rodzaj: 'tekst', postac: 'tekst' },
      { kod: 'variants', etykieta: 'Warianty', rodzaj: 'wielowiersz', postac: 'json' },
      { kod: 'tokenSetId', etykieta: 'Zestaw żetonów', rodzaj: 'tekst', postac: 'tekst' },
    ],
  },
  {
    grupa: 'makieta',
    komenda: Command.DesignComponentList,
    nazwa: 'Wykaz komponentów',
    okno: true,
    pola: [
      { kod: 'componentId', etykieta: 'Zawężenie do komponentu', rodzaj: 'tekst', postac: 'tekst' },
    ],
  },
  {
    grupa: 'makieta',
    komenda: Command.DesignComponentInstanceAdd,
    nazwa: 'Dołóż instancję komponentu',
    okno: false,
    pola: [
      { kod: 'componentId', etykieta: 'Komponent', rodzaj: 'tekst', postac: 'tekst', wymagane: true },
      { kod: 'boardId', etykieta: 'Kompozycja', rodzaj: 'tekst', postac: 'tekst', wymagane: true },
      { kod: 'variant', etykieta: 'Wariant', rodzaj: 'tekst', postac: 'tekst' },
      { kod: 'frameId', etykieta: 'Ramka', rodzaj: 'tekst', postac: 'tekst' },
      { kod: 'x', etykieta: 'X', rodzaj: 'liczba', postac: 'liczba' },
      { kod: 'y', etykieta: 'Y', rodzaj: 'liczba', postac: 'liczba' },
    ],
  },
  {
    grupa: 'makieta',
    komenda: Command.DesignPrototypeLinkSet,
    nazwa: 'Ustaw przejście prototypu',
    okno: false,
    pola: [
      { kod: 'boardId', etykieta: 'Kompozycja', rodzaj: 'tekst', postac: 'tekst', wymagane: true },
      { kod: 'fromFrameId', etykieta: 'Ramka źródłowa', rodzaj: 'tekst', postac: 'tekst', wymagane: true },
      { kod: 'toFrameId', etykieta: 'Ramka docelowa', rodzaj: 'tekst', postac: 'tekst', wymagane: true },
      { kod: 'trigger', etykieta: 'Wyzwalacz', rodzaj: 'wybor', postac: 'tekst', wymagane: true,
        pozycje: [
          { wartosc: 'click', etykieta: 'Kliknięcie' },
          { wartosc: 'hover', etykieta: 'Najechanie' },
          { wartosc: 'drag', etykieta: 'Przeciągnięcie' },
          { wartosc: 'afterDelay', etykieta: 'Po czasie' },
        ] },
      { kod: 'transition', etykieta: 'Przejście', rodzaj: 'wybor', postac: 'tekst', wymagane: true,
        pozycje: [
          { wartosc: 'instant', etykieta: 'Natychmiast' },
          { wartosc: 'dissolve', etykieta: 'Przenikanie' },
          { wartosc: 'slideLeft', etykieta: 'Wsuwanie w lewo' },
          { wartosc: 'slideRight', etykieta: 'Wsuwanie w prawo' },
          { wartosc: 'slideUp', etykieta: 'Wsuwanie w górę' },
          { wartosc: 'slideDown', etykieta: 'Wsuwanie w dół' },
          { wartosc: 'push', etykieta: 'Wypychanie' },
        ] },
      { kod: 'linkId', etykieta: 'Połączenie zmieniane', rodzaj: 'tekst', postac: 'tekst' },
      { kod: 'durationMs', etykieta: 'Czas przejścia (ms)', rodzaj: 'liczba', postac: 'liczba' },
      { kod: 'layerId', etykieta: 'Warstwa wyzwalająca', rodzaj: 'tekst', postac: 'tekst' },
    ],
  },
  {
    grupa: 'makieta',
    komenda: Command.DesignPrototypeGet,
    nazwa: 'Odczyt prototypu',
    okno: false,
    pola: [
      { kod: 'boardId', etykieta: 'Kompozycja', rodzaj: 'tekst', postac: 'tekst', wymagane: true },
      { kod: 'startFrameId', etykieta: 'Ramka początkowa', rodzaj: 'tekst', postac: 'tekst' },
    ],
  },
  {
    grupa: 'makieta',
    komenda: Command.DesignPrototypeLinkRemove,
    nazwa: 'Usuń przejście',
    okno: false,
    pola: [
      { kod: 'linkId', etykieta: 'Połączenie', rodzaj: 'tekst', postac: 'tekst', wymagane: true },
    ],
  },
  {
    grupa: 'makieta',
    komenda: Command.DesignMockupGenerate,
    nazwa: 'Zbuduj makietę z opisu',
    okno: true,
    pola: [
      { kod: 'boardId', etykieta: 'Kompozycja', rodzaj: 'tekst', postac: 'tekst', wymagane: true },
      { kod: 'prompt', etykieta: 'Opis ekranu', rodzaj: 'wielowiersz', postac: 'tekst', wymagane: true },
      { kod: 'devicePreset', etykieta: 'Nastawa urządzenia', rodzaj: 'tekst', postac: 'tekst' },
      { kod: 'tokenSetId', etykieta: 'Zestaw żetonów', rodzaj: 'tekst', postac: 'tekst' },
      { kod: 'channelId', etykieta: 'Kanał modelu obrazowego', rodzaj: 'tekst', postac: 'tekst' },
    ],
  },
  {
    grupa: 'makieta',
    komenda: Command.DesignMockupImport,
    nazwa: 'Wczytaj makietę ze zrzutu',
    okno: true,
    pola: [
      { kod: 'boardId', etykieta: 'Kompozycja', rodzaj: 'tekst', postac: 'tekst', wymagane: true },
      { kod: 'recognizeText', etykieta: 'Znacz linie tekstu', rodzaj: 'logiczne', postac: 'logiczne' },
      { kod: 'devicePreset', etykieta: 'Nastawa urządzenia', rodzaj: 'tekst', postac: 'tekst' },
      { kod: 'assetId', etykieta: 'Materiał', rodzaj: 'zasob', postac: 'tekst', wymagane: true },
    ],
  },
  {
    grupa: 'publikacja',
    komenda: Command.DesignProductMockupRender,
    nazwa: 'Wyrysuj makietę produktową',
    okno: true,
    pola: [
      { kod: 'designAssetId', etykieta: 'Projekt', rodzaj: 'zasob', postac: 'tekst', wymagane: true },
      { kod: 'productAssetId', etykieta: 'Zdjęcie produktu', rodzaj: 'zasob', postac: 'tekst', wymagane: true },
      { kod: 'x', etykieta: 'X nałożenia', rodzaj: 'liczba', postac: 'liczba', wymagane: true },
      { kod: 'y', etykieta: 'Y nałożenia', rodzaj: 'liczba', postac: 'liczba', wymagane: true },
      { kod: 'width', etykieta: 'Szerokość nałożenia', rodzaj: 'liczba', postac: 'liczba', wymagane: true },
      { kod: 'height', etykieta: 'Wysokość nałożenia', rodzaj: 'liczba', postac: 'liczba', wymagane: true },
      { kod: 'rotation', etykieta: 'Obrót (°)', rodzaj: 'liczba', postac: 'liczba' },
      { kod: 'opacity', etykieta: 'Krycie (0–1)', rodzaj: 'liczba', postac: 'liczba' },
    ],
  },
];
