/*
 * Danaco Console — rejestr-komend.ts
 *
 * PLIK GENEROWANY. Nie edytuj recznie — zmiany przepadna przy nastepnej generacji.
 *
 * Zrodlo prawdy: shared/contract.json
 * Generacja:     node shared/gen/generate.mjs
 *
 * Protokol: 1.0 · Transport: WebSocket, format JSON
 * Notacja:  obszar.zasob.akcja — nazwy komend i zdarzen po angielsku
 */

import { Command } from '../../../shared/contract.ts';

/** Pełny wykaz komend kontraktu — źródło wykazu katalogu operacji interfejsu. */
export const REJESTR_KOMEND: readonly Command[] = [
  Command.ConnectionHello,
  Command.HomeEnter,
  Command.EnvironmentList,
  Command.EnvironmentEnter,
  Command.ModuleList,
  Command.SpeechAvailabilityGet,
  Command.SpeechTranscribe,
  Command.WorkspaceEnter,
  Command.SessionCreate,
  Command.SessionList,
  Command.ProjectList,
  Command.ProjectCreate,
  Command.ProjectRename,
  Command.ProjectDelete,
  Command.SessionFocus,
  Command.SessionBind,
  Command.SessionOpen,
  Command.SessionExport,
  Command.SessionClose,
  Command.SessionDelete,
  Command.WindowCreate,
  Command.WindowList,
  Command.WindowStateGet,
  Command.WindowUpdate,
  Command.WindowClose,
  Command.MessageSend,
  Command.MessageStop,
  Command.MessageList,
  Command.ConfigGet,
  Command.ConfigSet,
  Command.ConfigReset,
  Command.ConfigSessionGet,
  Command.ConfigSessionSet,
  Command.ConfigEffectiveGet,
  Command.ConfigCapabilitiesGet,
  Command.ChannelAdd,
  Command.ChannelUpdate,
  Command.ChannelRemove,
  Command.ChannelList,
  Command.QueueCreate,
  Command.QueueAction,
  Command.ContextTransfer,
  Command.ActionList,
  Command.SettingsCategoryList,
  Command.SettingsDefinitionList,
  Command.AccessPointAdd,
  Command.AccessPointList,
  Command.AccessPointUpdate,
  Command.AccessPointRemove,
  Command.AccessPointCheck,
  Command.AccessGrantAdd,
  Command.AccessGrantList,
  Command.AccessGrantUpdate,
  Command.AccessGrantRemove,
  Command.AccountAdd,
  Command.AccountList,
  Command.AccountUpdate,
  Command.AccountRemove,
  Command.AccountDefaultSet,
  Command.IdentityCategoryList,
  Command.IdentityDocumentGet,
  Command.IdentityDocumentSet,
  Command.IdentityDocumentRemove,
  Command.IdentityEffectiveGet,
  Command.StudioDocumentOpen,
  Command.StudioDocumentSave,
  Command.StudioContextualOp,
  Command.StudioDiffCompare,
  Command.StudioRepositoryList,
  Command.StudioRepositoryRestore,
  Command.WorkspaceDashboardGet,
  Command.WorkspaceInstructionsSet,
  Command.WorkspaceContextSet,
  Command.WorkspaceContextGet,
  Command.WorkspaceLibraryList,
  Command.WorkspaceAgentAssign,
  Command.AutomationWorkflowSave,
  Command.AutomationWorkflowList,
  Command.AutomationScheduleSet,
  Command.AutomationQueueAction,
  Command.AutomationOrchestratorDefine,
  Command.AutomationExecutionSubscribe,
  Command.BrowserNavigate,
  Command.BrowserSnapshotGet,
  Command.BrowserSourceAdd,
  Command.BrowserNoteAdd,
  Command.BrowserSourceList,
  Command.BrowserNoteList,
  Command.ResearchSourceAdd,
  Command.ResearchFindingAdd,
  Command.ResearchReportBuild,
  Command.ResearchReportExport,
  Command.LibraryFileUpload,
  Command.LibraryFileList,
  Command.LibraryTagSet,
  Command.LibraryFilePreview,
  Command.LibraryVersionList,
  Command.TranslateSourceSet,
  Command.TranslateTargetAdd,
  Command.TranslateGlossarySet,
  Command.RoundtableModelAdd,
  Command.RoundtableDebateStart,
  Command.RoundtableModeratorDirect,
  Command.RoundtableConsensusGet,
  Command.DesignAssetGenerate,
  Command.DesignBoardUpdate,
  Command.DesignAssetList,
  Command.DesignAssetTagSet,
  Command.AssistantVoiceCommand,
  Command.AssistantActionStatus,
  Command.AssistantActivityList,
  Command.TerminalSessionOpen,
  Command.TerminalCommandExec,
  Command.TerminalProcessList,
  Command.TerminalProcessKill,
  Command.DeveloperFileOpen,
  Command.DeveloperFileSave,
  Command.DeveloperTreeGet,
  Command.DeveloperGitAction,
  Command.DeveloperBuildRun,
  Command.DiagnosticsLogQuery,
  Command.DiagnosticsErrorList,
  Command.DiagnosticsAnalyzeRun,
  Command.DiagnosticsRecommendationList,
  Command.AppsArchitectureDefine,
  Command.AppsWorkspaceUpdate,
  Command.AppsDeploymentRun,
  Command.AgentCreate,
  Command.AgentUpdate,
  Command.AgentList,
  Command.AgentDelete,
  Command.AgentModelSet,
  Command.AgentSkillAdd,
  Command.AgentConnectorAdd,
  Command.AgentPermissionSet,
  Command.AgentLayerSet,
  Command.AgentLayerRemove,
  Command.AgentPluginAdd,
  Command.AgentPluginRemove,
  Command.AgentPluginList,
  Command.AgentVersionList,
  Command.AgentVersionRestore,
  Command.AgentArchive,
  Command.AgentRestore,
  Command.AgentArchiveList,
  Command.WindowAction,
  Command.LibraryVersionAdd,
  Command.LibraryVersionRestore,
  Command.LibraryFileSearch,
  Command.LibraryCollectionCreate,
  Command.LibraryCollectionAssign,
  Command.TranslateTranslationSet,
  Command.ResearchWorkspaceSet,
  Command.TranslateBacktranslationRun,
  Command.TranslateQualityCheck,
  Command.TranslatePanelExport,
  Command.TranslatePanelToneSet,
  Command.TranslateSpeechSynthesize,
  Command.TranslateMemorySuggest,
  Command.TranslateSourceSegment,
  Command.TranslateSourceDetect,
  Command.TranslateGlossaryApply,
  Command.TranslateGlossaryOccurrences,
  Command.TranslateGlossaryImport,
  Command.TranslateGlossaryExport,
  Command.SessionRename,
  Command.SessionCopy,
  Command.SessionProjectSet,
  Command.SessionProjectClear,
  Command.SessionArchive,
  Command.SessionRestore,
  Command.SessionArchiveList,
  Command.SessionResume,
  Command.SessionStop,
  Command.WindowHandoff,
  Command.MemoryList,
  Command.MemorySet,
  Command.MemoryToggle,
  Command.MemoryDetach,
  Command.MemoryDelete,
  Command.OrchestrationDependencySet,
  Command.OrchestrationDependencyList,
  Command.OrchestrationDependencyRemove,
  Command.OrchestrationValidate,
  Command.IsolationScopeList,
  Command.IsolationContextGet,
  Command.IsolationContextSet,
  Command.IsolationTechnicalGet,
  Command.IsolationTechnicalSet,
  Command.IsolationProfileSave,
  Command.IsolationProfileList,
  Command.IsolationProfileLoad,
  Command.IsolationProfileAssign,
  Command.IsolationProfileDelete,
  Command.IsolationLayerSet,
  Command.IsolationPolicyPreview,
  Command.ComponentList,
  Command.ComponentCreate,
  Command.ComponentUpdate,
  Command.ComponentDelete,
  Command.ComponentAssign,
  Command.ExtensionList,
  Command.ExtensionInstall,
  Command.ExtensionConfigure,
  Command.ExtensionToggle,
  Command.ExtensionUninstall,
  Command.RoleAssign,
  Command.RoleUpdate,
  Command.SubagentSpawn,
  Command.SubagentList,
  Command.SubagentResultCollect,
  Command.SubagentStop,
  Command.AdvisorConsult,
  Command.MonitorSubscribe,
  Command.MonitorStatus,
  Command.ScheduleGet,
  Command.QueueList,
  Command.QueueLink,
  Command.ConfigExplainGet,
  Command.ConfigWindowOpen,
  Command.TerminalOutputStream,
  Command.TerminalOutputRead,
  Command.ModelChannelSet,
  Command.MobileStatusGet,
  Command.MobileProcessList,
  Command.MobileProcessControl,
  Command.AodStatusGet,
  Command.AodChatSend,
  Command.AodVoiceCommand,
  Command.AodContextGet,
  Command.AodSuggestion,
  Command.AodObserveAttach,
  Command.AodObserveDetach,
  Command.AuthRegister,
  Command.AuthVerify,
  Command.AuthRecover,
  Command.AuthReset,
  Command.AuthLogin,
  Command.AuthMethodAdd,
  Command.AuthMethodRemove,
  Command.AuthPasswordReset,
  Command.AuthTokenRefresh,
  Command.DeviceList,
  Command.DeviceRevoke,
  Command.TeamSave,
  Command.TeamLoad,
  Command.TeamList,
  Command.TeamDuplicate,
  Command.HistoryLoad,
  Command.HistoryDelete,
  Command.RetentionSet,
  Command.RoleList,
  Command.RoleRemove,
  Command.PanelSectionsGet,
  Command.PanelSectionsSet,
  Command.AppsDeploymentList,
  Command.AppsArchitectureGet,
  Command.AppsWorkspaceList,
  Command.DesignAssetUpload,
  Command.DesignAssetRemove,
  Command.DesignAssetFavoriteSet,
  Command.DesignBoardList,
  Command.ImageInspect,
  Command.ImageTransform,
  Command.ImageAdjust,
  Command.ImageConvert,
  Command.MediaInspect,
  Command.MediaTranscode,
  Command.DocumentConvert,
  Command.DocumentTextExtract,
  Command.ArchivePack,
  Command.ArchiveUnpack,
  Command.MailAccountList,
  Command.MailFolderList,
  Command.MailMessageList,
  Command.MailMessageGet,
  Command.MailDraftSave,
  Command.MailSend,
  Command.MailMessageFlag,
  Command.MailAccountAdd,
  Command.MailAccountDiscover,
  Command.MailAccountRemove,
  Command.ImageUpscale,
  Command.ImageBackgroundRemove,
  Command.KnowledgeIndex,
  Command.KnowledgeSearch,
  Command.KnowledgeImageSearch,
  Command.SessionToolAttach,
  Command.SessionToolDetach,
  Command.SessionToolList,
  Command.ToolsCatalogList,
  Command.AgentSkillRemove,
  Command.AgentConnectorList,
  Command.AgentConnectorRemove,
  Command.AgentConnectorConfigure,
  Command.AgentVersionGet,
  Command.AgentAssignmentList,
  Command.AgentModulesSet,
  Command.AgentIsolationGet,
  Command.AgentIsolationSet,
  Command.AgentPolicyGet,
  Command.AgentSubagentSet,
  Command.AgentPermissionRemove,
  Command.ChannelCheck,
  Command.ChannelCredentialStatus,
  Command.ExtensionSearch,
  Command.ExtensionDetailGet,
  Command.ExtensionCollectionList,
  Command.ExtensionCollectionSave,
  Command.ExtensionCollectionApply,
  Command.ExtensionRegistryList,
  Command.ExtensionUpdateCheck,
  Command.ExtensionPackageUpload,
  Command.ExtensionVersionPin,
  Command.ExtensionVersionRollback,
  Command.ExtensionBundleInstall,
  Command.ExtensionHistoryList,
  Command.ExtensionAdminBulk,
  Command.ExtensionToolList,
  Command.ExtensionToolCall,
  Command.ExtensionProtocolLogList,
  Command.ExtensionSandboxRun,
  Command.ExtensionDefinitionImport,
  Command.ExtensionTransportSet,
  Command.ExtensionCredentialBind,
  Command.ExtensionWebhookList,
  Command.ExtensionWebhookSave,
  Command.ExtensionMappingSave,
  Command.ExtensionUsageGet,
  Command.ExtensionHealthCheck,
  Command.ExtensionSecretList,
  Command.ExtensionSecretShare,
  Command.ExtensionPermissionList,
  Command.ExtensionPermissionGrant,
  Command.ExtensionSignatureVerify,
  Command.ExtensionManifestScan,
  Command.ExtensionAuditList,
  Command.AppsStageList,
  Command.AppsStageSave,
  Command.AppsProductGet,
  Command.AppsProductSave,
  Command.AppsProductLinkList,
  Command.AppsMilestoneList,
  Command.AppsMilestoneSave,
  Command.AppsMilestoneDelete,
  Command.AppsTimelineList,
  Command.AppsArchitectureValidate,
  Command.AppsArchitectureVersionList,
  Command.AppsArchitectureAnnotationSave,
  Command.AppsArchitectureExport,
  Command.AppsPreviewStart,
  Command.AppsPreviewStop,
  Command.AppsRouteList,
  Command.AppsThemeGet,
  Command.AppsThemeSet,
  Command.AppsEndpointList,
  Command.AppsEndpointProbe,
  Command.AppsEnvironmentList,
  Command.AppsEnvironmentVariableList,
  Command.AppsEnvironmentVariableSet,
  Command.AppsSchemaGet,
  Command.AppsServiceLogRead,
  Command.AppsArtifactList,
  Command.AppsDeploymentLogRead,
  Command.AppsDeploymentHealthGet,
  Command.AppsDeploymentDomainSet,
  Command.AppsDeploymentScaleSet,
  Command.AppsPackageBuild,
  Command.AppsPackageManifestSave,
  Command.AppsPackageValidate,
  Command.AppsPackageSign,
  Command.AppsPackagePublish,
  Command.SpeechAudioUpload,
  Command.SpeechAudioFetch,
  Command.SpeechWakeGet,
  Command.SpeechWakeSet,
  Command.SpeechListenStart,
  Command.SpeechListenStop,
  Command.AssistantActivityFlag,
  Command.MemoryRetentionGet,
  Command.MemoryRetentionSet,
  Command.MemoryContextList,
  Command.MemoryContextSave,
  Command.MemoryContextActivate,
  Command.MemoryContextDelete,
  Command.ToolsScopeList,
  Command.ToolsScopeSet,
  Command.ClipboardList,
  Command.ClipboardPush,
  Command.ClipboardPin,
  Command.ClipboardDelete,
  Command.SnippetList,
  Command.SnippetSet,
  Command.SnippetDelete,
  Command.LauncherHotkeyGet,
  Command.LauncherHotkeySet,
  Command.ContextUsageGet,
  Command.AutomationWorkflowSimulate,
  Command.AutomationWorkflowVersionList,
  Command.AutomationWorkflowVersionRestore,
  Command.AutomationWorkflowVersionDiff,
  Command.AutomationWorkflowTagSet,
  Command.AutomationWorkflowVariablesSet,
  Command.AutomationStepNoteSet,
  Command.AutomationStepLayoutSet,
  Command.AutomationTemplateSave,
  Command.AutomationTemplateList,
  Command.AutomationTemplateApply,
  Command.AutomationWorkflowPublish,
  Command.AutomationWorkflowShare,
  Command.ScheduleWindowSet,
  Command.ScheduleBackfillRun,
  Command.ScheduleTriggerHistory,
  Command.ScheduleHeartbeatSet,
  Command.ScheduleWebhookEndpointGet,
  Command.QueueItemEnqueue,
  Command.QueueItemDequeue,
  Command.QueueItemDelay,
  Command.QueueItemSplit,
  Command.QueueItemMerge,
  Command.QueueItemRoute,
  Command.QueueItemBranch,
  Command.QueueItemCondition,
  Command.QueueItemList,
  Command.QueuePolicySet,
  Command.QueueDeadList,
  Command.QueueDepthGet,
  Command.OrchestrationGateSet,
  Command.OrchestrationGroupSet,
  Command.OrchestrationCompensationSet,
  Command.OrchestrationMultitaskingLink,
  Command.AutomationExecutionLog,
  Command.AutomationExecutionSteps,
  Command.AutomationExecutionCheckpointList,
  Command.AutomationExecutionResume,
  Command.AutomationExecutionPayloadGet,
  Command.AutomationExecutionReplay,
  Command.AutomationAlertRuleSet,
  Command.AutomationAlertRuleList,
  Command.AutomationExecutionBudgetSet,
  Command.AutomationSecretSet,
  Command.AutomationSecretList,
  Command.AutomationSecretRemove,
  Command.AutomationAuditList,
  Command.BrowserMonitorAdd,
  Command.BrowserMonitorList,
  Command.BrowserMonitorCheck,
  Command.BrowserMonitorRemove,
  Command.BrowserFeedSubscribe,
  Command.BrowserFeedList,
  Command.BrowserFeedRemove,
  Command.BrowserReadlistAdd,
  Command.BrowserReadlistList,
  Command.BrowserReadlistRemove,
  Command.BrowserDomInspect,
  Command.BrowserNetworkHar,
  Command.BrowserConsoleRead,
  Command.BrowserDeviceEmulate,
  Command.BrowserScreenshotCapture,
  Command.BrowserSnapshotScreenshotGet,
  Command.BrowserExecutorLimitsSet,
  Command.BrowserExecutorLimitsGet,
  Command.BrowserSourceRemove,
  Command.BrowserNoteUpdate,
  Command.BrowserSourceGroupSet,
  Command.BrowserSourceGroupList,
  Command.BrowserNoteThreadSet,
  Command.BrowserNoteThreadList,
  Command.BrowserBookmarkAdd,
  Command.BrowserBookmarkList,
  Command.BrowserBookmarkRemove,
  Command.BrowserMacroRecord,
  Command.BrowserDownloadList,
  Command.BrowserDownloadControl,
  Command.BrowserScroll,
  Command.BrowserArtifactAdd,
  Command.BrowserTabOpen,
  Command.BrowserTabList,
  Command.BrowserTabUpdate,
  Command.BrowserTabClose,
  Command.BrowserTabGroupSet,
  Command.BrowserWorkspaceSave,
  Command.BrowserWorkspaceList,
  Command.BrowserWorkspaceOpen,
  Command.BrowserWorkspaceRemove,
  Command.DesignAssetContentGet,
  Command.DesignAssetExport,
  Command.DesignAssetExportBatch,
  Command.DesignCollectionCreate,
  Command.DesignCollectionAssign,
  Command.DesignCollectionList,
  Command.DesignPromptTemplateSave,
  Command.DesignPromptTemplateList,
  Command.DesignPromptHistoryList,
  Command.DesignBoardVersionSave,
  Command.DesignBoardVersionList,
  Command.DesignBoardVersionRestore,
  Command.DesignBoardExport,
  Command.DesignAnnotationSet,
  Command.DesignAnnotationList,
  Command.DesignPresenceReport,
  Command.DesignTokensetSave,
  Command.DesignTokensetList,
  Command.DesignTokensetExport,
  Command.DesignTokensetImport,
  Command.DesignStyleguidePublish,
  Command.ImageVectorize,
  Command.ImageLayersSplit,
  Command.ImageCompose,
  Command.DeveloperFileVersionList,
  Command.DeveloperFileVersionRestore,
  Command.DeveloperFileCreate,
  Command.DeveloperFileRename,
  Command.DeveloperFileDelete,
  Command.DeveloperFileMove,
  Command.DeveloperSymbolNavigate,
  Command.DeveloperFormatRun,
  Command.DeveloperLintGet,
  Command.DeveloperRefactorApply,
  Command.DeveloperGrepSearch,
  Command.DeveloperGrepReplace,
  Command.DeveloperGitStatus,
  Command.DeveloperGitDiff,
  Command.DeveloperGitLog,
  Command.DeveloperGitBranchList,
  Command.DeveloperGitConflictGet,
  Command.DeveloperGitConflictResolve,
  Command.DeveloperBuildList,
  Command.DeveloperBuildLogGet,
  Command.DeveloperTestResultGet,
  Command.DeveloperCoverageGet,
  Command.DeveloperDebugSessionStart,
  Command.DeveloperDebugSessionControl,
  Command.DeveloperBreakpointSet,
  Command.DeveloperDebugScopeGet,
  Command.DeveloperDebugEvaluate,
  Command.DeveloperApiRequest,
  Command.DeveloperApiCollectionSave,
  Command.DeveloperApiCollectionList,
  Command.DeveloperApiOpenapiImport,
  Command.DeveloperDataConnectionSet,
  Command.DeveloperDataConnectionList,
  Command.DeveloperDataSchemaGet,
  Command.DeveloperDataQueryRun,
  Command.DeveloperDataMigrationRun,
  Command.DeveloperContainerList,
  Command.DeveloperContainerAction,
  Command.DeveloperImageBuild,
  Command.DeveloperComposeUp,
  Command.DeveloperDependencyList,
  Command.DeveloperScanRun,
  Command.DeveloperScanResultList,
  Command.DeveloperContextualOp,
  Command.DeveloperToolchainCheck,
  Command.ProvenanceCallList,
  Command.ProvenanceCallGet,
  Command.ProvenanceCallReplay,
  Command.ProvenanceCallRate,
  Command.ProvenanceTraceExport,
  Command.UsageSummaryGet,
  Command.UsageReportBuild,
  Command.AlertRuleSave,
  Command.AlertRuleList,
  Command.AlertRuleRemove,
  Command.AlertTriggerList,
  Command.AlertTriggerAcknowledge,
  Command.HealthProbeSave,
  Command.HealthProbeList,
  Command.HealthProbeRemove,
  Command.HealthProbeRun,
  Command.HealthResultList,
  Command.HealthUptimeGet,
  Command.ResearchSourceList,
  Command.ResearchFindingList,
  Command.ResearchReportGet,
  Command.ResearchWorkspaceGet,
  Command.ResearchSourceUpdate,
  Command.ResearchSourceRemove,
  Command.ResearchSourceMerge,
  Command.ResearchSourceDuplicates,
  Command.ResearchSourceTag,
  Command.ResearchSourceAttachmentAdd,
  Command.ResearchSourceAttachmentList,
  Command.ResearchSourceImport,
  Command.ResearchSourceCapture,
  Command.ResearchSourceTranscribe,
  Command.ResearchSourceResolve,
  Command.ResearchDiscoverySearch,
  Command.ResearchDiscoveryAssist,
  Command.ResearchDiscoverySnowball,
  Command.ResearchDiscoveryReject,
  Command.ResearchMonitorSet,
  Command.ResearchMonitorList,
  Command.ResearchMonitorRefresh,
  Command.ResearchBatchImport,
  Command.ResearchReadingOpen,
  Command.ResearchAnnotationAdd,
  Command.ResearchAnnotationList,
  Command.ResearchAnnotationRemove,
  Command.ResearchExcerptList,
  Command.ResearchSourceSummarize,
  Command.ResearchSourceExtractTable,
  Command.ResearchSourceExtractClaims,
  Command.ResearchSourceOcr,
  Command.ResearchCorpusAsk,
  Command.ResearchFindingUpdate,
  Command.ResearchFindingRemove,
  Command.ResearchFindingCode,
  Command.ResearchCodebookGet,
  Command.ResearchCodebookSet,
  Command.ResearchFindingMatrix,
  Command.ResearchFindingContradictions,
  Command.ResearchContradictionResolve,
  Command.ResearchFindingFactCheck,
  Command.ResearchFindingCluster,
  Command.ResearchFindingMerge,
  Command.ResearchFindingProvenance,
  Command.ResearchWorkspaceQuestionSet,
  Command.ResearchWorkspaceCoverage,
  Command.ResearchWorkspaceNoteSet,
  Command.ResearchWorkspaceFreshness,
  Command.ResearchGapFind,
  Command.ResearchPrismaGet,
  Command.ResearchEvidenceGraph,
  Command.ResearchCitationRender,
  Command.ResearchCitationStyles,
  Command.ResearchCitationCheck,
  Command.ResearchRetractionCheck,
  Command.ResearchReportTemplateList,
  Command.ResearchReportSummarize,
  Command.ResearchReportBibliography,
  Command.ResearchReportFootnoteSet,
  Command.ResearchReportInsert,
  Command.ResearchReportVersionList,
  Command.ResearchReportDiff,
  Command.ResearchReportCommentAdd,
  Command.ResearchReportCommentList,
  Command.ResearchReportContextualOp,
  Command.ResearchExportPreview,
  Command.ResearchExportList,
  Command.ResearchExportTemplateSet,
  Command.ResearchExportTemplateList,
  Command.ResearchExportShare,
  Command.RoundtableDebateGet,
  Command.RoundtableModelList,
  Command.RoundtableModelRemove,
  Command.RoundtableModelUpdate,
  Command.RoundtableTeamSave,
  Command.RoundtableTeamList,
  Command.RoundtableTeamApply,
  Command.RoundtableRoleList,
  Command.RoundtableDebateFollowup,
  Command.RoundtableStatementRegenerate,
  Command.RoundtableDebateBranch,
  Command.RoundtableArgumentList,
  Command.RoundtableArgumentPin,
  Command.RoundtableArgumentExport,
  Command.RoundtableAnalysisRun,
  Command.RoundtableEvidenceList,
  Command.RoundtableAgreementGet,
  Command.RoundtableClusterGet,
  Command.RoundtableCruxGet,
  Command.RoundtableConvergenceGet,
  Command.RoundtableDriftGet,
  Command.RoundtableFallacyCatalogGet,
  Command.RoundtableFallacyCatalogSet,
  Command.RoundtableVoteStart,
  Command.RoundtableVoteCast,
  Command.RoundtableVoteGet,
  Command.RoundtableRatingSet,
  Command.RoundtableRubricSet,
  Command.RoundtableRubricList,
  Command.RoundtableJudgeRun,
  Command.RoundtableLeaderboardGet,
  Command.RoundtableDecisionMatrixSet,
  Command.RoundtableDecisionMatrixGet,
  Command.RoundtableCalibrationGet,
  Command.RoundtableConsensusSet,
  Command.RoundtableConsensusMinoritySet,
  Command.RoundtableConsensusVersionList,
  Command.RoundtableConsensusHandoff,
  Command.RoundtableModerationTemplateSave,
  Command.RoundtableModerationTemplateList,
  Command.RoundtableTranscriptExport,
  Command.RoundtableSpeechSynthesize,
  Command.StudioDocumentFormatSet,
  Command.StudioCommentAdd,
  Command.StudioCommentList,
  Command.StudioCommentResolve,
  Command.StudioTrackingSet,
  Command.StudioTrackingList,
  Command.StudioTrackingDecide,
  Command.StudioTemplateList,
  Command.StudioTemplateApply,
  Command.StudioAssetEmbed,
  Command.StudioOperationSave,
  Command.StudioOperationList,
  Command.StudioOperationDelete,
  Command.StudioChainSave,
  Command.StudioChainList,
  Command.StudioChainRun,
  Command.StudioBatchRun,
  Command.StudioAnnotationAdd,
  Command.StudioAnnotationList,
  Command.StudioDiffReportExport,
  Command.StudioDiffVisual,
  Command.StudioSearchSemantic,
  Command.StudioDiffSource,
  Command.StudioProposalDecide,
  Command.StudioVersionLabelSet,
  Command.StudioBranchCreate,
  Command.StudioBranchList,
  Command.StudioBranchMerge,
  Command.StudioRepositoryExport,
  Command.StudioPackageExport,
  Command.StudioVersionReferenceCreate,
  Command.StudioPreviewRender,
  Command.StudioExportProfileSave,
  Command.StudioExportProfileList,
  Command.StudioPdfMerge,
  Command.StudioPdfSplit,
  Command.StudioPdfPagesReorder,
  Command.StudioPdfOptimize,
  Command.StudioPdfStamp,
  Command.StudioPdfBates,
  Command.StudioPdfFormFill,
  Command.StudioPdfExtract,
  Command.StudioPdfBookmarksSet,
  Command.StudioSecurityEncrypt,
  Command.StudioSecuritySign,
  Command.StudioSecuritySignVerify,
  Command.StudioSecurityRedact,
  Command.StudioSecurityMetadataStrip,
  Command.StudioSecuritySensitiveDetect,
  Command.StudioIngestQueueAdd,
  Command.StudioIngestQueueList,
  Command.StudioIngestRecognize,
  Command.StudioIngestCorrectionSet,
  Command.StudioIngestItemAccept,
  Command.StudioIngestUrl,
  Command.StudioIngestDeviceScan,
  Command.StudioIngestDeviceList,
  Command.StudioDocumentFormGet,
  Command.StudioDocumentFormSave,
  Command.StudioTextGet,
  Command.StudioTextEdit,
  Command.StudioFormatCharacterSet,
  Command.StudioFormatCharacterGet,
  Command.StudioFormatParagraphSet,
  Command.StudioFormatParagraphGet,
  Command.StudioFormatClear,
  Command.StudioFormatCaseSet,
  Command.StudioFormatPainterCopy,
  Command.StudioFormatPainterApply,
  Command.StudioFormatSimilarSelect,
  Command.StudioFormatReplace,
  Command.StudioStyleList,
  Command.StudioStyleSave,
  Command.StudioStyleApply,
  Command.StudioStyleDelete,
  Command.StudioPageSetupGet,
  Command.StudioPageSetupSet,
  Command.StudioPagePaperList,
  Command.StudioPageEnvelopeSet,
  Command.StudioPageBreakInsert,
  Command.StudioPageHeaderfooterSet,
  Command.StudioPageHeaderfooterGet,
  Command.StudioPageNumberingSet,
  Command.StudioPageWatermarkSet,
  Command.StudioSectionSave,
  Command.StudioSectionList,
  Command.StudioSectionDelete,
  Command.StudioListApply,
  Command.StudioListBulletSet,
  Command.StudioListNumberingSet,
  Command.StudioListRestart,
  Command.StudioListLevelIndent,
  Command.StudioTableInsert,
  Command.StudioTableStructureEdit,
  Command.StudioTableFormatSet,
  Command.StudioTableSort,
  Command.StudioTableConvert,
  Command.StudioTableList,
  Command.StudioObjectInsert,
  Command.StudioObjectFormatSet,
  Command.StudioObjectList,
  Command.StudioObjectRemove,
  Command.StudioSymbolInsert,
  Command.StudioSymbolList,
  Command.StudioSymbolAutoreplaceSet,
  Command.StudioSymbolAutoreplaceList,
  Command.StudioFieldInsert,
  Command.StudioFieldRefresh,
  Command.StudioFieldList,
  Command.StudioApparatusInsert,
  Command.StudioApparatusList,
  Command.StudioApparatusRemove,
  Command.StudioApparatusRefresh,
  Command.StudioDocumentCreate,
  Command.StudioDocumentImportFile,
  Command.StudioDocumentImportPdf,
  Command.StudioDocumentImageImport,
  Command.StudioDocumentSaveAs,
  Command.StudioDocumentCopy,
  Command.StudioDocumentExportFormat,
  Command.StudioDocumentExportBatch,
  Command.StudioTemplateSave,
  Command.StudioTemplateDelete,
  Command.StudioTemplateFieldSet,
  Command.StudioTemplateFieldList,
  Command.StudioTemplateImport,
  Command.StudioTemplateExport,
  Command.StudioTemplateFill,
  Command.StudioLockAdd,
  Command.StudioLockRemove,
  Command.StudioLockList,
  Command.StudioJournalList,
  Command.StudioJournalRevert,
  Command.StudioJournalRedo,
  Command.StudioModelChangesList,
  Command.StudioModelChangesRevert,
  Command.StudioModelChangesNavigate,
  Command.StudioDiffFormCompare,
  Command.StudioDiffHunkApply,
  Command.StudioAutosaveSet,
  Command.StudioAutosaveGet,
  Command.StudioAutosaveRun,
  Command.StudioBackupCreate,
  Command.StudioBackupList,
  Command.StudioBackupRestore,
  Command.StudioVersionRestoreInitial,
  Command.StudioVersionSeriesList,
  Command.StudioViewGet,
  Command.StudioViewSet,
  Command.StudioRulerTabstopSet,
  Command.StudioMarkupAdd,
  Command.StudioMarkupList,
  Command.StudioMarkupRemove,
  Command.StudioMarkupDecide,
  Command.StudioMarkupTypeSave,
  Command.StudioMarkupTypeList,
  Command.StudioMarkupTypeDelete,
  Command.StudioClipboardCopy,
  Command.StudioClipboardPaste,
  Command.StudioInsertFromLibrary,
  Command.StudioInsertFromWeb,
  Command.StudioProvenanceList,
  Command.StudioAgentsSettingsGet,
  Command.StudioAgentsSettingsSet,
  Command.StudioPlanCreate,
  Command.StudioPlanGet,
  Command.StudioPlanTaskUpdate,
  Command.StudioPlanRun,
  Command.StudioPlanStop,
  Command.StudioAgentsClaim,
  Command.StudioAgentsRelease,
  Command.StudioAgentsSlotsList,
  Command.StudioAgentsConflictsList,
  Command.TerminalSessionClose,
  Command.TerminalSessionList,
  Command.TerminalFileRead,
  Command.TerminalProcessSuspend,
  Command.TerminalHostSave,
  Command.TerminalHostList,
  Command.TerminalHostRemove,
  Command.TerminalScriptSave,
  Command.TerminalScriptList,
  Command.TerminalScriptRemove,
  Command.TerminalScriptLint,
  Command.TerminalTunnelOpen,
  Command.TerminalTunnelList,
  Command.TerminalTunnelClose,
  Command.TerminalKeyGenerate,
  Command.TerminalKeyImport,
  Command.TerminalKeyList,
  Command.TerminalKeyRemove,
  Command.TerminalWatchStart,
  Command.TerminalWatchStop,
  Command.TerminalWatchList,
  Command.TranslateMemoryList,
  Command.TranslateMemorySet,
  Command.TranslateMemoryDelete,
  Command.TranslateMemoryImport,
  Command.TranslateMemoryExport,
  Command.TranslateMemoryMaintain,
  Command.TranslateMemoryPretranslate,
  Command.TranslateMemoryAlign,
  Command.TranslateMemoryPolicyGet,
  Command.TranslateMemoryPolicySet,
  Command.TranslateSegmentationRulesList,
  Command.TranslateSegmentationRulesSet,
  Command.TranslateSegmentMerge,
  Command.TranslateSegmentSplit,
  Command.TranslateGlossaryList,
  Command.TranslateTermExtract,
  Command.TranslateProofreadRun,
  Command.TranslateProofreadApply,
  Command.TranslateConsistencyCheck,
  Command.TranslateQaProfileList,
  Command.TranslateQaProfileSet,
  Command.TranslateQaProfileDelete,
  Command.TranslateApprovalSet,
  Command.TranslateApprovalList,
  Command.TranslateDocumentLoad,
  Command.TranslateDocumentRender,
  Command.TranslateDocumentLayoutCompare,
  Command.TranslateResourceImport,
  Command.TranslateResourceExport,
  Command.TranslateResourcePluralApply,
  Command.TranslateResourceKeyContextSet,
  Command.TranslateXliffImport,
  Command.TranslateSubtitleImport,
  Command.TranslateSubtitleExport,
  Command.TranslateSubtitleTimingCheck,
  Command.TranslateDubbingScriptBuild,
  Command.TranslatePivotPolicyGet,
  Command.TranslatePivotPolicySet,
  Command.TranslateBatchRun,
  Command.TranslateEngineProfileList,
  Command.TranslateEngineProfileSet,
  Command.TranslateEngineCompare,
  Command.TranslateHandoffBuild,
  Command.TranslateHandoffReceive,
  Command.TranslateBridgeSourceReceive,
  Command.TranslateBridgeResultSend,
  Command.TranslateArtifactPublish,
  Command.TranslateStepList,
  Command.WorkspaceAgentUnassign,
  Command.WorkspaceProjectStatusSet,
  Command.WorkspaceInstructionsVersionList,
  Command.WorkspaceInstructionsVersionRestore,
  Command.WorkspaceTaskCreate,
  Command.WorkspaceTaskUpdate,
  Command.WorkspaceTaskDelete,
  Command.WorkspaceTaskList,
  Command.WorkspaceTaskMove,
  Command.WorkspaceTaskDependencySet,
  Command.WorkspaceTaskDependencyRemove,
  Command.WorkspaceBoardGet,
  Command.WorkspaceScheduleGet,
  Command.WorkspaceCalendarGet,
  Command.WorkspaceCalendarImport,
  Command.WorkspaceCalendarExport,
  Command.WorkspaceNoteSave,
  Command.WorkspaceNoteGet,
  Command.WorkspaceNoteList,
  Command.WorkspaceNoteDelete,
  Command.WorkspaceNoteTreeGet,
  Command.WorkspaceNoteBacklinkList,
  Command.WorkspaceKnowledgeGraphGet,
  Command.WorkspaceCanvasGet,
  Command.WorkspaceCanvasSave,
  Command.WorkspaceLibraryTextExtract,
  Command.WorkspaceLibraryDuplicateList,
  Command.WorkspaceLibraryDuplicateMerge,
  Command.WorkspaceSearchProject,
  Command.WorkspaceActivityList,
  Command.WorkspaceCommentAdd,
  Command.WorkspaceCommentList,
  Command.WorkspaceCommentDelete,
  Command.LibraryMetadataGet,
  Command.LibraryMetadataSet,
  Command.LibrarySchemaGet,
  Command.LibrarySchemaSet,
  Command.LibraryTagList,
  Command.LibraryTagUpdate,
  Command.LibraryTagMerge,
  Command.LibraryTagRemove,
  Command.LibraryCollectionList,
  Command.LibraryThesaurusRelate,
  Command.LibraryThesaurusExport,
  Command.LibraryRuleSet,
  Command.LibraryRuleList,
  Command.LibraryRuleRemove,
  Command.LibraryDuplicateScan,
  Command.LibraryDuplicateMerge,
  Command.LibraryFixityCheck,
  Command.LibraryNameNormalize,
  Command.LibraryAuditList,
  Command.LibraryStatsGet,
  Command.LibraryRetentionSet,
  Command.LibraryRetentionList,
  Command.LibraryPreservationRun,
  Command.LibraryPackageExport,
  Command.LibraryFileMove,
  Command.LibraryFileArchive,
  Command.LibraryFileRestore,
  Command.LibraryFileDelete,
  Command.LibraryShareCreate,
  Command.LibraryShareList,
  Command.LibraryShareRevoke,
  Command.LibraryWebhookSet,
  Command.LibraryWebhookList,
  Command.LibraryWebhookRemove,
  Command.LibraryClassifyRun,
  Command.LibrarySuggestionList,
  Command.LibrarySuggestionApply,
  Command.LibraryDiffCompare,
  Command.DesignVectorPathSet,
  Command.DesignVectorPathList,
  Command.DesignVectorPathRemove,
  Command.DesignVectorShapeAdd,
  Command.DesignVectorBoolean,
  Command.DesignVectorTextPath,
  Command.DesignVectorOptimize,
  Command.DesignVectorSymbolSet,
  Command.DesignVectorSymbolList,
  Command.DesignVectorExport,
  Command.DesignFrameSet,
  Command.DesignFrameList,
  Command.DesignFrameRemove,
  Command.DesignLayoutAuto,
  Command.DesignConstraintSet,
  Command.DesignFrameResizeApply,
  Command.DesignComponentSave,
  Command.DesignComponentList,
  Command.DesignComponentInstanceAdd,
  Command.DesignPrototypeLinkSet,
  Command.DesignPrototypeGet,
  Command.DesignPrototypeLinkRemove,
  Command.DesignMockupGenerate,
  Command.DesignMockupImport,
  Command.DesignGridSet,
  Command.DesignColorPaletteGenerate,
  Command.DesignColorPaletteExtract,
  Command.DesignColorContrastCheck,
  Command.DesignColorVisionSimulate,
  Command.DesignColorGradientSet,
  Command.DesignColorConvert,
  Command.DesignColorAccessibilityAudit,
  Command.DesignIconLibrarySearch,
  Command.DesignIconSet,
  Command.DesignIconGenerate,
  Command.DesignIconSpriteBuild,
  Command.DesignFaviconBuild,
  Command.DesignFontPairSuggest,
  Command.DesignFontPreview,
  Command.DesignFontGlyphsGet,
  Command.DesignTemplateSave,
  Command.DesignTemplateList,
  Command.DesignTemplateApply,
  Command.DesignCampaignSetBuild,
  Command.DesignStockSearch,
  Command.DesignStockImport,
  Command.DesignProductMockupRender,
  Command.DesignPrintProfileSet,
  Command.DesignPrintProfileList,
  Command.DesignPrintPreflight,
  Command.DesignPrintExport,
  Command.DesignPrintPaperList,
  Command.DesignLargeformatTile,
  Command.DesignChartRender,
  Command.DesignDiagramRender,
  Command.DesignPhotoCrop,
  Command.DesignPhotoTransform,
  Command.DesignPhotoResample,
  Command.DesignPhotoUpscale,
  Command.DesignPhotoEnhance,
  Command.DesignPhotoColorCorrect,
  Command.DesignPhotoFilterApply,
  Command.DesignPhotoRetouch,
  Command.DesignPhotoInpaint,
  Command.DesignPhotoExpand,
  Command.DesignPhotoBackgroundRemove,
  Command.DesignPhotoSelectObject,
  Command.DesignPhotoMaskSet,
  Command.DesignPhotoLayerComposite,
  Command.DesignPhotoBatchApply,
  Command.DesignPhotoPresetSave,
  Command.DesignPhotoPresetList,
  Command.DesignPhotoVectorize,
  Command.DesignPhotoMetadataGet,
  Command.DesignPhotoHistoryGet,
  Command.AodMuteGet,
  Command.AodMuteSet,
  Command.AodSignalReport,
  Command.AodSignalList,
  Command.MemoryDisableList,
  Command.MemoryDisableSet,
  Command.NotificationList,
  Command.NotificationAcknowledge,
  Command.NotificationResolve,
  Command.NotificationSnooze,
  Command.BrowserAccessibilityAudit,
  Command.AppsPerformanceAudit,
  Command.DeveloperApiLoadRun,
];

/** Pola, bez których rdzeń odmawia operacji — katalog podaje z nich kształt żądania. */
export const POLA_WYMAGANE: ReadonlyMap<Command, readonly string[]> = new Map([
  [Command.ConnectionHello, ['clientId', 'clientVersion', 'protocolVersion']],
  [Command.HomeEnter, ['clientId']],
  [Command.EnvironmentEnter, ['environmentId', 'clientId']],
  [Command.SpeechTranscribe, ['audioRef']],
  [Command.WorkspaceEnter, ['sessionId', 'moduleId']],
  [Command.ProjectCreate, ['name']],
  [Command.ProjectRename, ['projectId', 'name']],
  [Command.ProjectDelete, ['projectId']],
  [Command.SessionFocus, ['sessionId', 'clientId']],
  [Command.SessionBind, ['sessionId', 'clientId']],
  [Command.SessionOpen, ['sessionId']],
  [Command.SessionExport, ['sessionId']],
  [Command.SessionClose, ['sessionId']],
  [Command.SessionDelete, ['sessionIds', 'confirm']],
  [Command.WindowCreate, ['sessionId', 'moduleId', 'modelChannelId', 'workingDirs', 'executionEnv', 'permissionMode', 'windowRole']],
  [Command.WindowStateGet, ['windowId']],
  [Command.WindowUpdate, ['windowId']],
  [Command.WindowClose, ['windowId']],
  [Command.MessageSend, ['windowId', 'content']],
  [Command.MessageStop, ['windowId']],
  [Command.MessageList, ['windowId']],
  [Command.ConfigSet, ['key', 'value', 'scope']],
  [Command.ConfigReset, ['scope']],
  [Command.ConfigSessionSet, ['areas', 'config', 'scope']],
  [Command.ChannelAdd, ['name', 'kind']],
  [Command.ChannelUpdate, ['channelId']],
  [Command.ChannelRemove, ['channelId']],
  [Command.QueueCreate, ['sessionId']],
  [Command.QueueAction, ['queueId', 'action']],
  [Command.ContextTransfer, ['sourceWindowId', 'targetModuleId', 'bundle']],
  [Command.AccessPointAdd, ['name', 'kind', 'roots', 'defaultMode']],
  [Command.AccessPointUpdate, ['accessPointId']],
  [Command.AccessPointRemove, ['accessPointId']],
  [Command.AccessPointCheck, ['accessPointId']],
  [Command.AccessGrantAdd, ['windowId', 'accessPointId', 'mode']],
  [Command.AccessGrantUpdate, ['grantId']],
  [Command.AccessGrantRemove, ['grantId']],
  [Command.AccountAdd, ['name', 'kind', 'provider']],
  [Command.AccountUpdate, ['accountId']],
  [Command.AccountRemove, ['accountId']],
  [Command.AccountDefaultSet, ['accountId', 'kind']],
  [Command.IdentityDocumentSet, ['categoryId', 'content']],
  [Command.IdentityDocumentRemove, ['documentId']],
  [Command.StudioDocumentOpen, ['windowId']],
  [Command.StudioDocumentSave, ['documentId', 'content']],
  [Command.StudioContextualOp, ['windowId', 'documentId', 'actionId', 'scope']],
  [Command.StudioDiffCompare, ['documentId']],
  [Command.StudioRepositoryList, ['documentId']],
  [Command.StudioRepositoryRestore, ['documentId', 'versionId']],
  [Command.WorkspaceDashboardGet, ['projectId']],
  [Command.WorkspaceInstructionsSet, ['projectId', 'content']],
  [Command.WorkspaceContextSet, ['projectId', 'content']],
  [Command.WorkspaceContextGet, ['projectId']],
  [Command.WorkspaceLibraryList, ['projectId']],
  [Command.WorkspaceAgentAssign, ['projectId', 'agentId']],
  [Command.AutomationWorkflowSave, ['name']],
  [Command.AutomationScheduleSet, ['workflowId']],
  [Command.AutomationQueueAction, ['queueId', 'action']],
  [Command.AutomationOrchestratorDefine, ['workflowId']],
  [Command.BrowserNavigate, ['windowId', 'url']],
  [Command.BrowserSnapshotGet, ['windowId']],
  [Command.BrowserSourceAdd, ['windowId', 'url']],
  [Command.BrowserNoteAdd, ['windowId', 'content']],
  [Command.BrowserSourceList, ['windowId']],
  [Command.BrowserNoteList, ['windowId']],
  [Command.ResearchSourceAdd, ['windowId', 'title', 'kind']],
  [Command.ResearchFindingAdd, ['windowId', 'content']],
  [Command.ResearchReportBuild, ['windowId']],
  [Command.ResearchReportExport, ['reportId', 'format']],
  [Command.LibraryFileUpload, ['name']],
  [Command.LibraryTagSet, ['fileId']],
  [Command.LibraryFilePreview, ['fileId']],
  [Command.LibraryVersionList, ['fileId']],
  [Command.TranslateSourceSet, ['windowId', 'text']],
  [Command.TranslateTargetAdd, ['windowId', 'language']],
  [Command.TranslateGlossarySet, ['source', 'language']],
  [Command.RoundtableModelAdd, ['windowId', 'channelId']],
  [Command.RoundtableDebateStart, ['windowId', 'question']],
  [Command.RoundtableModeratorDirect, ['windowId', 'action']],
  [Command.RoundtableConsensusGet, ['windowId']],
  [Command.DesignAssetGenerate, ['windowId', 'prompt']],
  [Command.DesignBoardUpdate, ['windowId']],
  [Command.DesignAssetTagSet, ['assetId', 'tags']],
  [Command.AssistantVoiceCommand, ['windowId']],
  [Command.TerminalSessionOpen, ['windowId', 'shell']],
  [Command.TerminalCommandExec, ['sessionId', 'command']],
  [Command.TerminalProcessKill, ['processId']],
  [Command.DeveloperFileOpen, ['windowId', 'path']],
  [Command.DeveloperFileSave, ['windowId', 'path', 'content']],
  [Command.DeveloperTreeGet, ['windowId']],
  [Command.DeveloperGitAction, ['windowId', 'action']],
  [Command.DeveloperBuildRun, ['windowId', 'task']],
  [Command.AppsArchitectureDefine, ['windowId']],
  [Command.AppsWorkspaceUpdate, ['windowId', 'layer', 'path', 'content']],
  [Command.AppsDeploymentRun, ['windowId', 'environment']],
  [Command.AgentCreate, ['name']],
  [Command.AgentUpdate, ['agentId']],
  [Command.AgentDelete, ['agentId']],
  [Command.AgentModelSet, ['agentId', 'channelId']],
  [Command.AgentSkillAdd, ['agentId', 'skillId']],
  [Command.AgentConnectorAdd, ['agentId', 'name', 'kind']],
  [Command.AgentPermissionSet, ['agentId', 'group', 'granted']],
  [Command.AgentLayerSet, ['agentId', 'layer', 'content']],
  [Command.AgentLayerRemove, ['agentId', 'layer']],
  [Command.AgentPluginAdd, ['agentId', 'name']],
  [Command.AgentPluginRemove, ['agentId', 'pluginId']],
  [Command.AgentPluginList, ['agentId']],
  [Command.AgentVersionList, ['agentId']],
  [Command.AgentVersionRestore, ['agentId', 'versionId']],
  [Command.AgentArchive, ['agentId']],
  [Command.AgentRestore, ['agentId']],
  [Command.WindowAction, ['windowId', 'actionId']],
  [Command.LibraryVersionAdd, ['fileId']],
  [Command.LibraryVersionRestore, ['fileId', 'versionId']],
  [Command.LibraryFileSearch, ['query']],
  [Command.LibraryCollectionCreate, ['name']],
  [Command.LibraryCollectionAssign, ['collectionId', 'fileIds']],
  [Command.TranslateTranslationSet, ['panelId', 'text']],
  [Command.ResearchWorkspaceSet, ['scope']],
  [Command.TranslateBacktranslationRun, ['panelId']],
  [Command.TranslateQualityCheck, ['panelId']],
  [Command.TranslatePanelExport, ['panelId', 'format']],
  [Command.TranslatePanelToneSet, ['panelId', 'tone']],
  [Command.TranslateSpeechSynthesize, ['panelId']],
  [Command.TranslateMemorySuggest, ['panelId', 'segment']],
  [Command.TranslateGlossaryOccurrences, ['term']],
  [Command.TranslateGlossaryImport, ['path']],
  [Command.TranslateGlossaryExport, ['path']],
  [Command.SessionRename, ['sessionId', 'title']],
  [Command.SessionCopy, ['sessionId']],
  [Command.SessionProjectSet, ['sessionIds']],
  [Command.SessionProjectClear, ['sessionIds']],
  [Command.SessionArchive, ['sessionIds']],
  [Command.SessionRestore, ['sessionIds']],
  [Command.SessionResume, ['sessionId']],
  [Command.SessionStop, ['sessionId']],
  [Command.WindowHandoff, ['sessionId', 'fromWindowId', 'toWindowId', 'instruction']],
  [Command.MemorySet, ['content']],
  [Command.MemoryToggle, ['sessionId']],
  [Command.MemoryDetach, ['entryId']],
  [Command.MemoryDelete, ['entryId']],
  [Command.OrchestrationDependencySet, ['workflowId', 'dependency']],
  [Command.OrchestrationDependencyList, ['workflowId']],
  [Command.OrchestrationDependencyRemove, ['workflowId', 'fromStepId', 'toStepId']],
  [Command.OrchestrationValidate, ['workflowId']],
  [Command.IsolationContextGet, ['scope']],
  [Command.IsolationContextSet, ['scope', 'switches']],
  [Command.IsolationTechnicalGet, ['scope']],
  [Command.IsolationTechnicalSet, ['scope', 'switches']],
  [Command.IsolationProfileSave, ['name']],
  [Command.IsolationProfileLoad, ['profileId']],
  [Command.IsolationProfileAssign, ['profileId', 'scope']],
  [Command.IsolationProfileDelete, ['profileId']],
  [Command.IsolationLayerSet, ['layer']],
  [Command.ComponentCreate, ['kind', 'name']],
  [Command.ComponentUpdate, ['componentId']],
  [Command.ComponentDelete, ['componentId']],
  [Command.ComponentAssign, ['componentId', 'scope']],
  [Command.ExtensionInstall, ['code', 'kind']],
  [Command.ExtensionConfigure, ['extensionId', 'config']],
  [Command.ExtensionToggle, ['extensionId', 'enabled']],
  [Command.ExtensionUninstall, ['extensionId']],
  [Command.RoleAssign, ['windowId', 'role']],
  [Command.RoleUpdate, ['windowId']],
  [Command.SubagentSpawn, ['windowId', 'task']],
  [Command.AdvisorConsult, ['windowId', 'question']],
  [Command.QueueLink, ['queueId']],
  [Command.TerminalOutputRead, ['processId']],
  [Command.ModelChannelSet, ['modelChannelId']],
  [Command.MobileProcessControl, ['processId', 'control']],
  [Command.AodChatSend, ['text']],
  [Command.AodObserveAttach, ['processId']],
  [Command.AodObserveDetach, ['processId']],
  [Command.AuthRegister, ['login', 'email', 'password']],
  [Command.AuthVerify, ['token']],
  [Command.AuthRecover, ['email']],
  [Command.AuthReset, ['token', 'newPassword']],
  [Command.AuthLogin, ['method']],
  [Command.AuthMethodAdd, ['kind', 'deviceId']],
  [Command.AuthMethodRemove, ['methodId']],
  [Command.AuthPasswordReset, ['currentPassword', 'newPassword']],
  [Command.DeviceRevoke, ['deviceId']],
  [Command.TeamSave, ['name', 'agentIds']],
  [Command.TeamLoad, ['teamId']],
  [Command.TeamDuplicate, ['teamId']],
  [Command.HistoryLoad, ['windowId']],
  [Command.HistoryDelete, ['windowId']],
  [Command.RetentionSet, ['scope']],
  [Command.RoleRemove, ['windowId']],
  [Command.PanelSectionsGet, ['windowId', 'panelId']],
  [Command.PanelSectionsSet, ['windowId', 'panelId', 'sections']],
  [Command.AppsDeploymentList, ['windowId']],
  [Command.AppsArchitectureGet, ['windowId']],
  [Command.AppsWorkspaceList, ['windowId']],
  [Command.DesignAssetUpload, ['windowId', 'kind']],
  [Command.DesignAssetRemove, ['assetId']],
  [Command.DesignAssetFavoriteSet, ['assetId', 'favorite']],
  [Command.DesignBoardList, ['windowId']],
  [Command.ImageTransform, ['operation']],
  [Command.ImageAdjust, ['operation']],
  [Command.ImageConvert, ['format']],
  [Command.MediaTranscode, ['operation']],
  [Command.DocumentConvert, ['toFormat']],
  [Command.MailMessageGet, ['messageId']],
  [Command.MailMessageFlag, ['messageId']],
  [Command.MailAccountAdd, ['address']],
  [Command.MailAccountRemove, ['accountId']],
  [Command.KnowledgeSearch, ['query']],
  [Command.KnowledgeImageSearch, ['query']],
  [Command.SessionToolAttach, ['sessionId', 'toolName']],
  [Command.SessionToolDetach, ['sessionId', 'toolName']],
  [Command.SessionToolList, ['sessionId']],
  [Command.AgentSkillRemove, ['agentId', 'skillId']],
  [Command.AgentConnectorList, ['agentId']],
  [Command.AgentConnectorRemove, ['agentId', 'connectorId']],
  [Command.AgentConnectorConfigure, ['agentId', 'connectorId']],
  [Command.AgentVersionGet, ['agentId', 'versionId']],
  [Command.AgentModulesSet, ['agentId', 'moduleCodes']],
  [Command.AgentIsolationGet, ['agentId']],
  [Command.AgentIsolationSet, ['agentId', 'switches']],
  [Command.AgentPolicyGet, ['agentId']],
  [Command.AgentSubagentSet, ['agentId', 'enabled']],
  [Command.AgentPermissionRemove, ['agentId']],
  [Command.ChannelCheck, ['channelId']],
  [Command.ChannelCredentialStatus, ['channelId']],
  [Command.ExtensionSearch, ['query']],
  [Command.ExtensionDetailGet, ['extensionId']],
  [Command.ExtensionCollectionSave, ['name', 'extensionIds']],
  [Command.ExtensionCollectionApply, ['collectionId']],
  [Command.ExtensionPackageUpload, ['fileName', 'contentBase64']],
  [Command.ExtensionVersionPin, ['extensionId']],
  [Command.ExtensionVersionRollback, ['extensionId', 'targetVersion']],
  [Command.ExtensionBundleInstall, ['manifest']],
  [Command.ExtensionAdminBulk, ['extensionIds', 'action']],
  [Command.ExtensionToolList, ['extensionId']],
  [Command.ExtensionToolCall, ['extensionId', 'toolName']],
  [Command.ExtensionProtocolLogList, ['extensionId']],
  [Command.ExtensionSandboxRun, ['extensionId', 'input']],
  [Command.ExtensionDefinitionImport, ['format', 'code']],
  [Command.ExtensionTransportSet, ['extensionId', 'transport']],
  [Command.ExtensionCredentialBind, ['extensionId', 'authKind', 'credentialRef']],
  [Command.ExtensionWebhookSave, ['extensionId', 'direction']],
  [Command.ExtensionMappingSave, ['extensionId', 'name', 'rules']],
  [Command.ExtensionSecretShare, ['secretRef']],
  [Command.ExtensionPermissionList, ['extensionId']],
  [Command.ExtensionPermissionGrant, ['extensionId', 'permissions']],
  [Command.ExtensionSignatureVerify, ['extensionId']],
  [Command.ExtensionManifestScan, ['extensionId']],
  [Command.AppsStageList, ['windowId']],
  [Command.AppsStageSave, ['windowId']],
  [Command.AppsProductGet, ['windowId']],
  [Command.AppsProductSave, ['windowId', 'name']],
  [Command.AppsProductLinkList, ['windowId']],
  [Command.AppsMilestoneList, ['windowId']],
  [Command.AppsMilestoneSave, ['windowId', 'name']],
  [Command.AppsMilestoneDelete, ['windowId', 'milestoneId']],
  [Command.AppsTimelineList, ['windowId']],
  [Command.AppsArchitectureValidate, ['windowId']],
  [Command.AppsArchitectureVersionList, ['windowId']],
  [Command.AppsArchitectureAnnotationSave, ['windowId', 'text']],
  [Command.AppsArchitectureExport, ['windowId', 'format']],
  [Command.AppsPreviewStart, ['windowId']],
  [Command.AppsPreviewStop, ['windowId']],
  [Command.AppsRouteList, ['windowId']],
  [Command.AppsThemeGet, ['windowId']],
  [Command.AppsThemeSet, ['windowId', 'theme']],
  [Command.AppsEndpointList, ['windowId']],
  [Command.AppsEndpointProbe, ['windowId', 'method', 'path']],
  [Command.AppsEnvironmentList, ['windowId']],
  [Command.AppsEnvironmentVariableList, ['windowId', 'environment']],
  [Command.AppsEnvironmentVariableSet, ['windowId', 'environment', 'name']],
  [Command.AppsSchemaGet, ['windowId']],
  [Command.AppsServiceLogRead, ['windowId']],
  [Command.AppsArtifactList, ['windowId']],
  [Command.AppsDeploymentLogRead, ['windowId', 'deploymentId']],
  [Command.AppsDeploymentHealthGet, ['windowId']],
  [Command.AppsDeploymentDomainSet, ['windowId', 'environment', 'domain']],
  [Command.AppsDeploymentScaleSet, ['windowId', 'environment']],
  [Command.AppsPackageBuild, ['windowId']],
  [Command.AppsPackageManifestSave, ['windowId', 'manifest']],
  [Command.AppsPackageValidate, ['windowId', 'packageId']],
  [Command.AppsPackageSign, ['windowId', 'packageId', 'signingKeyRef']],
  [Command.AppsPackagePublish, ['windowId', 'packageId']],
  [Command.SpeechAudioUpload, ['audio', 'contentType']],
  [Command.SpeechAudioFetch, ['audioRef']],
  [Command.SpeechListenStart, ['windowId']],
  [Command.AssistantActivityFlag, ['entryId', 'important']],
  [Command.MemoryContextSave, ['name']],
  [Command.MemoryContextActivate, ['contextId', 'sessionId']],
  [Command.MemoryContextDelete, ['contextId']],
  [Command.ToolsScopeSet, ['profileId', 'toolName']],
  [Command.ClipboardPush, ['content']],
  [Command.ClipboardPin, ['entryId', 'pinned']],
  [Command.SnippetSet, ['shortcut', 'content']],
  [Command.SnippetDelete, ['snippetId']],
  [Command.LauncherHotkeySet, ['hotkey']],
  [Command.ContextUsageGet, ['windowId']],
  [Command.AutomationWorkflowSimulate, ['workflowId']],
  [Command.AutomationWorkflowVersionList, ['workflowId']],
  [Command.AutomationWorkflowVersionRestore, ['workflowId', 'version']],
  [Command.AutomationWorkflowVersionDiff, ['workflowId', 'fromVersion', 'toVersion']],
  [Command.AutomationWorkflowTagSet, ['workflowId', 'tags']],
  [Command.AutomationWorkflowVariablesSet, ['workflowId', 'variables']],
  [Command.AutomationStepNoteSet, ['workflowId', 'stepId', 'note']],
  [Command.AutomationStepLayoutSet, ['workflowId', 'positions']],
  [Command.AutomationTemplateSave, ['workflowId', 'name']],
  [Command.AutomationTemplateApply, ['templateId', 'name']],
  [Command.AutomationWorkflowPublish, ['workflowId']],
  [Command.AutomationWorkflowShare, ['workflowId', 'shared']],
  [Command.ScheduleWindowSet, ['scheduleId', 'windows']],
  [Command.ScheduleBackfillRun, ['scheduleId', 'fromAt', 'toAt']],
  [Command.ScheduleHeartbeatSet, ['scheduleId', 'toleranceSeconds']],
  [Command.ScheduleWebhookEndpointGet, ['workflowId']],
  [Command.QueueItemEnqueue, ['queueId', 'payload']],
  [Command.QueueItemDequeue, ['queueId', 'itemId']],
  [Command.QueueItemDelay, ['queueId', 'itemId', 'delaySeconds']],
  [Command.QueueItemSplit, ['queueId', 'itemId', 'payloads']],
  [Command.QueueItemMerge, ['queueId', 'itemIds']],
  [Command.QueueItemRoute, ['queueId', 'itemId']],
  [Command.QueueItemBranch, ['queueId', 'itemId', 'branches']],
  [Command.QueueItemCondition, ['queueId', 'itemId', 'condition']],
  [Command.QueueItemList, ['queueId']],
  [Command.QueuePolicySet, ['queueId', 'policy']],
  [Command.QueueDepthGet, ['fromAt', 'bucketSeconds']],
  [Command.OrchestrationGateSet, ['workflowId', 'stepId', 'rule']],
  [Command.OrchestrationGroupSet, ['workflowId', 'name', 'stepIds', 'kind']],
  [Command.OrchestrationCompensationSet, ['workflowId', 'stepId']],
  [Command.OrchestrationMultitaskingLink, ['workflowId', 'linked']],
  [Command.AutomationExecutionLog, ['executionId']],
  [Command.AutomationExecutionSteps, ['executionId']],
  [Command.AutomationExecutionCheckpointList, ['executionId']],
  [Command.AutomationExecutionResume, ['executionId']],
  [Command.AutomationExecutionPayloadGet, ['executionId', 'stepId']],
  [Command.AutomationExecutionReplay, ['executionId']],
  [Command.AutomationAlertRuleSet, ['workflowId', 'trigger', 'channels']],
  [Command.AutomationExecutionBudgetSet, ['workflowId']],
  [Command.AutomationSecretSet, ['name', 'value']],
  [Command.AutomationSecretRemove, ['secretRef']],
  [Command.BrowserMonitorAdd, ['windowId', 'url']],
  [Command.BrowserMonitorCheck, ['monitorId']],
  [Command.BrowserMonitorRemove, ['monitorId']],
  [Command.BrowserFeedSubscribe, ['windowId', 'url']],
  [Command.BrowserFeedRemove, ['feedId']],
  [Command.BrowserReadlistAdd, ['windowId', 'url']],
  [Command.BrowserReadlistRemove, ['itemId']],
  [Command.BrowserDomInspect, ['windowId']],
  [Command.BrowserNetworkHar, ['windowId']],
  [Command.BrowserConsoleRead, ['windowId']],
  [Command.BrowserDeviceEmulate, ['windowId']],
  [Command.BrowserScreenshotCapture, ['windowId', 'mode']],
  [Command.BrowserSourceRemove, ['sourceId']],
  [Command.BrowserNoteUpdate, ['noteId']],
  [Command.BrowserSourceGroupSet, ['windowId', 'name']],
  [Command.BrowserSourceGroupList, ['windowId']],
  [Command.BrowserNoteThreadSet, ['windowId', 'name']],
  [Command.BrowserNoteThreadList, ['windowId']],
  [Command.BrowserBookmarkAdd, ['windowId', 'url']],
  [Command.BrowserBookmarkRemove, ['bookmarkId']],
  [Command.BrowserMacroRecord, ['windowId', 'action']],
  [Command.BrowserDownloadControl, ['downloadId', 'action']],
  [Command.BrowserScroll, ['windowId']],
  [Command.BrowserArtifactAdd, ['windowId', 'kind']],
  [Command.BrowserTabOpen, ['windowId']],
  [Command.BrowserTabList, ['windowId']],
  [Command.BrowserTabUpdate, ['tabId']],
  [Command.BrowserTabClose, ['tabId']],
  [Command.BrowserTabGroupSet, ['windowId', 'name']],
  [Command.BrowserWorkspaceSave, ['windowId', 'name']],
  [Command.BrowserWorkspaceOpen, ['workspaceId', 'windowId']],
  [Command.BrowserWorkspaceRemove, ['workspaceId']],
  [Command.DesignAssetContentGet, ['assetId']],
  [Command.DesignAssetExport, ['assetId', 'format']],
  [Command.DesignAssetExportBatch, ['assetIds', 'format']],
  [Command.DesignCollectionCreate, ['windowId', 'name']],
  [Command.DesignCollectionAssign, ['collectionId', 'assetIds']],
  [Command.DesignCollectionList, ['windowId']],
  [Command.DesignPromptTemplateSave, ['windowId', 'name', 'prompt']],
  [Command.DesignPromptTemplateList, ['windowId']],
  [Command.DesignPromptHistoryList, ['windowId']],
  [Command.DesignBoardVersionSave, ['boardId']],
  [Command.DesignBoardVersionList, ['boardId']],
  [Command.DesignBoardVersionRestore, ['versionId']],
  [Command.DesignBoardExport, ['boardId', 'format']],
  [Command.DesignAnnotationSet, ['boardId', 'text']],
  [Command.DesignAnnotationList, ['boardId']],
  [Command.DesignPresenceReport, ['boardId']],
  [Command.DesignTokensetSave, ['windowId', 'name', 'tokens']],
  [Command.DesignTokensetList, ['windowId']],
  [Command.DesignTokensetExport, ['tokenSetId', 'target']],
  [Command.DesignTokensetImport, ['windowId', 'name', 'contentBase64']],
  [Command.DesignStyleguidePublish, ['tokenSetId', 'targetModuleId']],
  [Command.ImageCompose, ['baseAssetId', 'overlayAssetId']],
  [Command.DeveloperFileVersionList, ['windowId', 'path']],
  [Command.DeveloperFileVersionRestore, ['windowId', 'versionId']],
  [Command.DeveloperFileCreate, ['windowId', 'path', 'kind']],
  [Command.DeveloperFileRename, ['windowId', 'path', 'newName']],
  [Command.DeveloperFileDelete, ['windowId', 'paths']],
  [Command.DeveloperFileMove, ['windowId', 'paths', 'targetPath']],
  [Command.DeveloperSymbolNavigate, ['windowId', 'path', 'line', 'column', 'kind']],
  [Command.DeveloperFormatRun, ['windowId', 'path']],
  [Command.DeveloperLintGet, ['windowId']],
  [Command.DeveloperRefactorApply, ['windowId', 'path', 'line', 'column', 'kind']],
  [Command.DeveloperGrepSearch, ['windowId', 'pattern']],
  [Command.DeveloperGrepReplace, ['windowId', 'pattern', 'replacement']],
  [Command.DeveloperGitStatus, ['windowId']],
  [Command.DeveloperGitDiff, ['windowId']],
  [Command.DeveloperGitLog, ['windowId']],
  [Command.DeveloperGitBranchList, ['windowId']],
  [Command.DeveloperGitConflictGet, ['windowId', 'path']],
  [Command.DeveloperGitConflictResolve, ['windowId', 'path', 'resolution']],
  [Command.DeveloperBuildList, ['windowId']],
  [Command.DeveloperBuildLogGet, ['buildId']],
  [Command.DeveloperTestResultGet, ['buildId']],
  [Command.DeveloperCoverageGet, ['buildId']],
  [Command.DeveloperDebugSessionStart, ['windowId']],
  [Command.DeveloperDebugSessionControl, ['sessionId', 'step']],
  [Command.DeveloperBreakpointSet, ['windowId', 'path', 'line']],
  [Command.DeveloperDebugScopeGet, ['sessionId']],
  [Command.DeveloperDebugEvaluate, ['sessionId', 'frameId', 'expression']],
  [Command.DeveloperApiRequest, ['windowId', 'method', 'url']],
  [Command.DeveloperApiCollectionSave, ['windowId', 'name', 'requests']],
  [Command.DeveloperApiCollectionList, ['windowId']],
  [Command.DeveloperApiOpenapiImport, ['windowId']],
  [Command.DeveloperDataConnectionSet, ['windowId', 'name', 'engine', 'database']],
  [Command.DeveloperDataConnectionList, ['windowId']],
  [Command.DeveloperDataSchemaGet, ['connectionId']],
  [Command.DeveloperDataQueryRun, ['connectionId', 'sql']],
  [Command.DeveloperDataMigrationRun, ['connectionId', 'windowId', 'direction']],
  [Command.DeveloperContainerList, ['windowId']],
  [Command.DeveloperContainerAction, ['containerId', 'action']],
  [Command.DeveloperImageBuild, ['windowId', 'dockerfile', 'tag']],
  [Command.DeveloperComposeUp, ['windowId', 'file']],
  [Command.DeveloperDependencyList, ['windowId']],
  [Command.DeveloperScanRun, ['windowId', 'kinds']],
  [Command.DeveloperContextualOp, ['windowId', 'operation']],
  [Command.DeveloperToolchainCheck, ['programs']],
  [Command.ProvenanceCallGet, ['callId']],
  [Command.ProvenanceCallReplay, ['callId']],
  [Command.ProvenanceCallRate, ['callId', 'quality']],
  [Command.ProvenanceTraceExport, ['format']],
  [Command.UsageSummaryGet, ['dimension']],
  [Command.UsageReportBuild, ['format']],
  [Command.AlertRuleSave, ['name', 'kind', 'metric', 'windowMs', 'severity', 'channels']],
  [Command.AlertRuleRemove, ['ruleId']],
  [Command.AlertTriggerAcknowledge, ['triggerId']],
  [Command.HealthProbeSave, ['name', 'kind', 'target', 'intervalMs']],
  [Command.HealthProbeRemove, ['probeId']],
  [Command.HealthProbeRun, ['probeId']],
  [Command.ResearchSourceList, ['windowId']],
  [Command.ResearchFindingList, ['windowId']],
  [Command.ResearchReportGet, ['windowId']],
  [Command.ResearchSourceUpdate, ['sourceId']],
  [Command.ResearchSourceRemove, ['sourceId']],
  [Command.ResearchSourceMerge, ['targetSourceId', 'mergedSourceIds']],
  [Command.ResearchSourceDuplicates, ['windowId']],
  [Command.ResearchSourceTag, ['sourceId']],
  [Command.ResearchSourceAttachmentAdd, ['sourceId', 'kind']],
  [Command.ResearchSourceAttachmentList, ['sourceId']],
  [Command.ResearchSourceImport, ['windowId', 'format']],
  [Command.ResearchSourceCapture, ['windowId', 'url', 'mode']],
  [Command.ResearchSourceTranscribe, ['windowId']],
  [Command.ResearchSourceResolve, ['identifier']],
  [Command.ResearchDiscoverySearch, ['windowId', 'query', 'mode']],
  [Command.ResearchDiscoveryAssist, ['question']],
  [Command.ResearchDiscoverySnowball, ['direction']],
  [Command.ResearchDiscoveryReject, ['windowId', 'resultKeys', 'reason']],
  [Command.ResearchMonitorSet, ['windowId', 'kind']],
  [Command.ResearchMonitorList, ['windowId']],
  [Command.ResearchMonitorRefresh, ['windowId']],
  [Command.ResearchBatchImport, ['windowId', 'urls']],
  [Command.ResearchReadingOpen, ['sourceId']],
  [Command.ResearchAnnotationAdd, ['sourceId', 'kind', 'anchor']],
  [Command.ResearchAnnotationRemove, ['annotationId']],
  [Command.ResearchExcerptList, ['windowId']],
  [Command.ResearchSourceSummarize, ['sourceId']],
  [Command.ResearchSourceExtractTable, ['sourceId']],
  [Command.ResearchSourceExtractClaims, ['sourceId']],
  [Command.ResearchSourceOcr, ['sourceId']],
  [Command.ResearchCorpusAsk, ['windowId', 'question']],
  [Command.ResearchFindingUpdate, ['findingId']],
  [Command.ResearchFindingRemove, ['findingId']],
  [Command.ResearchFindingCode, ['findingId']],
  [Command.ResearchCodebookGet, ['windowId']],
  [Command.ResearchCodebookSet, ['windowId', 'codes']],
  [Command.ResearchFindingMatrix, ['windowId']],
  [Command.ResearchFindingContradictions, ['windowId']],
  [Command.ResearchContradictionResolve, ['contradictionId', 'rationale']],
  [Command.ResearchFindingFactCheck, ['findingId']],
  [Command.ResearchFindingCluster, ['windowId']],
  [Command.ResearchFindingMerge, ['targetFindingId', 'mergedFindingIds']],
  [Command.ResearchFindingProvenance, ['findingId']],
  [Command.ResearchWorkspaceQuestionSet, ['questions']],
  [Command.ResearchWorkspaceCoverage, ['windowId']],
  [Command.ResearchWorkspaceNoteSet, ['content']],
  [Command.ResearchWorkspaceFreshness, ['windowId']],
  [Command.ResearchGapFind, ['windowId']],
  [Command.ResearchPrismaGet, ['windowId']],
  [Command.ResearchEvidenceGraph, ['windowId']],
  [Command.ResearchCitationRender, ['sourceIds', 'styleId', 'mode']],
  [Command.ResearchCitationCheck, ['windowId']],
  [Command.ResearchRetractionCheck, ['sourceIds']],
  [Command.ResearchReportSummarize, ['reportId']],
  [Command.ResearchReportBibliography, ['reportId', 'styleId', 'scope']],
  [Command.ResearchReportFootnoteSet, ['reportId', 'placement']],
  [Command.ResearchReportInsert, ['reportId', 'sectionId', 'kind']],
  [Command.ResearchReportVersionList, ['reportId']],
  [Command.ResearchReportDiff, ['reportId', 'baseVersionId', 'targetVersionId']],
  [Command.ResearchReportCommentAdd, ['reportId', 'content']],
  [Command.ResearchReportCommentList, ['reportId']],
  [Command.ResearchReportContextualOp, ['reportId', 'sectionId', 'actionId']],
  [Command.ResearchExportPreview, ['reportId', 'format']],
  [Command.ResearchExportTemplateSet, ['name', 'format', 'content']],
  [Command.ResearchExportShare, ['reportId']],
  [Command.RoundtableDebateGet, ['windowId']],
  [Command.RoundtableModelList, ['windowId']],
  [Command.RoundtableModelRemove, ['windowId', 'participantId']],
  [Command.RoundtableModelUpdate, ['windowId', 'participantId']],
  [Command.RoundtableTeamSave, ['windowId', 'name']],
  [Command.RoundtableTeamApply, ['windowId', 'teamId']],
  [Command.RoundtableDebateFollowup, ['windowId', 'participantId', 'question']],
  [Command.RoundtableStatementRegenerate, ['windowId', 'statementId']],
  [Command.RoundtableDebateBranch, ['windowId', 'turnId']],
  [Command.RoundtableArgumentList, ['windowId']],
  [Command.RoundtableArgumentPin, ['windowId', 'nodeId', 'pinned']],
  [Command.RoundtableArgumentExport, ['windowId', 'format']],
  [Command.RoundtableAnalysisRun, ['windowId', 'kind']],
  [Command.RoundtableEvidenceList, ['windowId']],
  [Command.RoundtableAgreementGet, ['windowId']],
  [Command.RoundtableClusterGet, ['windowId']],
  [Command.RoundtableCruxGet, ['windowId']],
  [Command.RoundtableConvergenceGet, ['windowId']],
  [Command.RoundtableDriftGet, ['windowId']],
  [Command.RoundtableFallacyCatalogSet, ['windowId', 'codes']],
  [Command.RoundtableVoteStart, ['windowId', 'method', 'options']],
  [Command.RoundtableVoteCast, ['windowId', 'voteId', 'voterId']],
  [Command.RoundtableVoteGet, ['windowId']],
  [Command.RoundtableRatingSet, ['windowId', 'kind']],
  [Command.RoundtableRubricSet, ['name', 'criteria']],
  [Command.RoundtableJudgeRun, ['windowId', 'rubricId', 'judgeParticipantIds']],
  [Command.RoundtableLeaderboardGet, ['scope']],
  [Command.RoundtableDecisionMatrixSet, ['windowId', 'name', 'criteria', 'options']],
  [Command.RoundtableDecisionMatrixGet, ['windowId']],
  [Command.RoundtableCalibrationGet, ['windowId']],
  [Command.RoundtableConsensusSet, ['windowId', 'content']],
  [Command.RoundtableConsensusMinoritySet, ['windowId', 'consensusId', 'participantId', 'content']],
  [Command.RoundtableConsensusVersionList, ['windowId']],
  [Command.RoundtableConsensusHandoff, ['windowId', 'consensusId', 'target']],
  [Command.RoundtableModerationTemplateSave, ['windowId', 'name']],
  [Command.RoundtableTranscriptExport, ['windowId', 'format']],
  [Command.RoundtableSpeechSynthesize, ['windowId']],
  [Command.StudioDocumentFormatSet, ['documentId', 'format']],
  [Command.StudioCommentAdd, ['documentId', 'body']],
  [Command.StudioCommentList, ['documentId']],
  [Command.StudioCommentResolve, ['commentId', 'resolved']],
  [Command.StudioTrackingSet, ['documentId', 'enabled']],
  [Command.StudioTrackingList, ['documentId']],
  [Command.StudioTrackingDecide, ['documentId', 'changeIds', 'accept']],
  [Command.StudioTemplateApply, ['windowId', 'templateId']],
  [Command.StudioAssetEmbed, ['documentId', 'assetId']],
  [Command.StudioOperationSave, ['name', 'category', 'prompt']],
  [Command.StudioOperationDelete, ['operationId']],
  [Command.StudioChainSave, ['name', 'steps']],
  [Command.StudioChainRun, ['windowId', 'documentId', 'chainId', 'scope']],
  [Command.StudioBatchRun, ['windowId', 'documentIds', 'actionId']],
  [Command.StudioAnnotationAdd, ['documentId', 'hunkIndex', 'body']],
  [Command.StudioAnnotationList, ['documentId']],
  [Command.StudioDiffReportExport, ['documentId', 'baseVersionId', 'format']],
  [Command.StudioDiffVisual, ['documentId', 'baseVersionId', 'targetVersionId']],
  [Command.StudioSearchSemantic, ['documentId', 'query']],
  [Command.StudioDiffSource, ['documentId']],
  [Command.StudioProposalDecide, ['documentId', 'proposalId', 'accept']],
  [Command.StudioVersionLabelSet, ['versionId']],
  [Command.StudioBranchCreate, ['documentId', 'fromVersionId', 'name']],
  [Command.StudioBranchList, ['documentId']],
  [Command.StudioBranchMerge, ['sourceBranchId', 'targetBranchId']],
  [Command.StudioRepositoryExport, ['documentId']],
  [Command.StudioPackageExport, ['documentId']],
  [Command.StudioVersionReferenceCreate, ['versionId']],
  [Command.StudioPreviewRender, ['documentId', 'format']],
  [Command.StudioExportProfileSave, ['name', 'format']],
  [Command.StudioPdfMerge, ['assetIds']],
  [Command.StudioPdfSplit, ['assetId']],
  [Command.StudioPdfPagesReorder, ['assetId', 'operations']],
  [Command.StudioPdfOptimize, ['assetId']],
  [Command.StudioPdfStamp, ['assetId']],
  [Command.StudioPdfBates, ['assetId']],
  [Command.StudioPdfFormFill, ['assetId']],
  [Command.StudioPdfExtract, ['assetId']],
  [Command.StudioPdfBookmarksSet, ['assetId', 'bookmarks']],
  [Command.StudioSecurityEncrypt, ['assetId']],
  [Command.StudioSecuritySign, ['assetId', 'certificateId']],
  [Command.StudioSecuritySignVerify, ['assetId']],
  [Command.StudioSecurityRedact, ['assetId', 'regions']],
  [Command.StudioSecurityMetadataStrip, ['assetId']],
  [Command.StudioSecuritySensitiveDetect, ['documentId']],
  [Command.StudioIngestQueueAdd, ['windowId']],
  [Command.StudioIngestQueueList, ['windowId']],
  [Command.StudioIngestRecognize, ['itemId']],
  [Command.StudioIngestCorrectionSet, ['itemId', 'wordIndex', 'text']],
  [Command.StudioIngestItemAccept, ['windowId', 'itemIds']],
  [Command.StudioIngestUrl, ['windowId', 'url']],
  [Command.StudioIngestDeviceScan, ['windowId']],
  [Command.StudioDocumentFormGet, ['documentId']],
  [Command.StudioDocumentFormSave, ['documentId', 'form']],
  [Command.StudioTextGet, ['documentId']],
  [Command.StudioTextEdit, ['documentId', 'rangeStart', 'rangeEnd', 'text']],
  [Command.StudioFormatCharacterSet, ['documentId']],
  [Command.StudioFormatCharacterGet, ['documentId']],
  [Command.StudioFormatParagraphSet, ['documentId']],
  [Command.StudioFormatParagraphGet, ['documentId']],
  [Command.StudioFormatClear, ['documentId']],
  [Command.StudioFormatCaseSet, ['documentId', 'transform']],
  [Command.StudioFormatPainterCopy, ['documentId']],
  [Command.StudioFormatPainterApply, ['documentId', 'clipId']],
  [Command.StudioFormatSimilarSelect, ['documentId']],
  [Command.StudioFormatReplace, ['documentId']],
  [Command.StudioStyleList, ['documentId']],
  [Command.StudioStyleSave, ['documentId', 'name']],
  [Command.StudioStyleApply, ['documentId', 'name']],
  [Command.StudioStyleDelete, ['documentId', 'name']],
  [Command.StudioPageSetupGet, ['documentId']],
  [Command.StudioPageSetupSet, ['documentId']],
  [Command.StudioPageEnvelopeSet, ['documentId']],
  [Command.StudioPageBreakInsert, ['documentId', 'offset', 'kind']],
  [Command.StudioPageHeaderfooterSet, ['documentId', 'scope']],
  [Command.StudioPageHeaderfooterGet, ['documentId']],
  [Command.StudioPageNumberingSet, ['documentId', 'enabled']],
  [Command.StudioPageWatermarkSet, ['documentId', 'kind']],
  [Command.StudioSectionSave, ['documentId']],
  [Command.StudioSectionList, ['documentId']],
  [Command.StudioSectionDelete, ['documentId', 'sectionId']],
  [Command.StudioListApply, ['documentId', 'kind']],
  [Command.StudioListBulletSet, ['documentId', 'listId', 'level']],
  [Command.StudioListNumberingSet, ['documentId', 'listId', 'level']],
  [Command.StudioListRestart, ['documentId', 'listId', 'offset']],
  [Command.StudioListLevelIndent, ['documentId', 'step']],
  [Command.StudioTableInsert, ['documentId', 'offset', 'rows', 'columns']],
  [Command.StudioTableStructureEdit, ['documentId', 'tableId', 'operation']],
  [Command.StudioTableFormatSet, ['documentId', 'tableId']],
  [Command.StudioTableSort, ['documentId', 'tableId', 'column']],
  [Command.StudioTableConvert, ['documentId', 'direction']],
  [Command.StudioTableList, ['documentId']],
  [Command.StudioObjectInsert, ['documentId', 'offset', 'kind']],
  [Command.StudioObjectFormatSet, ['documentId', 'objectId']],
  [Command.StudioObjectList, ['documentId']],
  [Command.StudioObjectRemove, ['documentId', 'objectId']],
  [Command.StudioSymbolInsert, ['documentId', 'offset']],
  [Command.StudioSymbolAutoreplaceSet, ['shortcut']],
  [Command.StudioFieldInsert, ['documentId', 'offset', 'kind']],
  [Command.StudioFieldRefresh, ['documentId']],
  [Command.StudioFieldList, ['documentId']],
  [Command.StudioApparatusInsert, ['documentId', 'kind']],
  [Command.StudioApparatusList, ['documentId']],
  [Command.StudioApparatusRemove, ['documentId', 'itemId']],
  [Command.StudioApparatusRefresh, ['documentId']],
  [Command.StudioDocumentCreate, ['windowId']],
  [Command.StudioDocumentImportFile, ['windowId']],
  [Command.StudioDocumentImportPdf, ['windowId']],
  [Command.StudioDocumentImageImport, ['documentId', 'offset', 'source']],
  [Command.StudioDocumentSaveAs, ['documentId']],
  [Command.StudioDocumentCopy, ['documentId']],
  [Command.StudioDocumentExportFormat, ['documentId', 'format']],
  [Command.StudioDocumentExportBatch, ['documentIds', 'format']],
  [Command.StudioTemplateSave, ['name']],
  [Command.StudioTemplateDelete, ['templateId']],
  [Command.StudioTemplateFieldSet, ['templateId', 'name']],
  [Command.StudioTemplateFieldList, ['templateId']],
  [Command.StudioTemplateExport, ['templateId']],
  [Command.StudioTemplateFill, ['templateId', 'values']],
  [Command.StudioLockAdd, ['documentId', 'rangeStart', 'rangeEnd', 'name']],
  [Command.StudioLockRemove, ['documentId', 'lockId']],
  [Command.StudioLockList, ['documentId']],
  [Command.StudioJournalList, ['documentId']],
  [Command.StudioJournalRevert, ['documentId', 'actionIds']],
  [Command.StudioJournalRedo, ['documentId', 'actionIds']],
  [Command.StudioModelChangesList, ['documentId']],
  [Command.StudioModelChangesRevert, ['documentId']],
  [Command.StudioModelChangesNavigate, ['documentId', 'direction']],
  [Command.StudioDiffFormCompare, ['documentId']],
  [Command.StudioDiffHunkApply, ['documentId', 'sourceVersionId']],
  [Command.StudioAutosaveSet, ['enabled']],
  [Command.StudioAutosaveRun, ['documentId']],
  [Command.StudioBackupCreate, ['documentId']],
  [Command.StudioBackupRestore, ['backupId']],
  [Command.StudioVersionRestoreInitial, ['documentId']],
  [Command.StudioVersionSeriesList, ['documentId']],
  [Command.StudioRulerTabstopSet, ['documentId', 'positionMm']],
  [Command.StudioMarkupAdd, ['documentId', 'kind', 'rangeStart', 'rangeEnd']],
  [Command.StudioMarkupList, ['documentId']],
  [Command.StudioMarkupRemove, ['documentId', 'markupId']],
  [Command.StudioMarkupDecide, ['documentId', 'markupIds', 'accept']],
  [Command.StudioMarkupTypeSave, ['name']],
  [Command.StudioMarkupTypeDelete, ['name']],
  [Command.StudioClipboardCopy, ['documentId', 'rangeStart', 'rangeEnd']],
  [Command.StudioClipboardPaste, ['documentId', 'offset']],
  [Command.StudioInsertFromLibrary, ['documentId', 'offset', 'libraryFileId']],
  [Command.StudioInsertFromWeb, ['documentId', 'offset', 'url']],
  [Command.StudioProvenanceList, ['documentId']],
  [Command.StudioPlanCreate, ['documentId', 'order']],
  [Command.StudioPlanTaskUpdate, ['taskId']],
  [Command.StudioPlanRun, ['planId']],
  [Command.StudioPlanStop, ['planId']],
  [Command.StudioAgentsClaim, ['documentId', 'rangeStart', 'rangeEnd']],
  [Command.StudioAgentsRelease, ['documentId']],
  [Command.StudioAgentsSlotsList, ['documentId']],
  [Command.StudioAgentsConflictsList, ['documentId']],
  [Command.TerminalSessionClose, ['sessionId']],
  [Command.TerminalFileRead, ['sessionId', 'path']],
  [Command.TerminalProcessSuspend, ['processId']],
  [Command.TerminalHostSave, ['host']],
  [Command.TerminalHostRemove, ['hostId']],
  [Command.TerminalScriptSave, ['script']],
  [Command.TerminalScriptRemove, ['scriptId']],
  [Command.TerminalScriptLint, ['content', 'shell']],
  [Command.TerminalTunnelOpen, ['windowId', 'kind']],
  [Command.TerminalTunnelClose, ['tunnelId']],
  [Command.TerminalKeyGenerate, ['name', 'keyType']],
  [Command.TerminalKeyImport, ['name', 'path']],
  [Command.TerminalKeyRemove, ['keyId']],
  [Command.TerminalWatchStart, ['sessionId', 'pattern', 'command']],
  [Command.TerminalWatchStop, ['watchId']],
  [Command.TranslateMemorySet, ['language', 'sourceSegment', 'targetSegment']],
  [Command.TranslateMemoryDelete, ['entryId']],
  [Command.TranslateMemoryImport, ['path']],
  [Command.TranslateMemoryExport, ['path']],
  [Command.TranslateMemoryMaintain, ['kind']],
  [Command.TranslateMemoryPretranslate, ['windowId']],
  [Command.TranslateMemoryAlign, ['sourceText', 'targetText', 'language']],
  [Command.TranslateMemoryPolicyGet, ['windowId']],
  [Command.TranslateMemoryPolicySet, ['windowId']],
  [Command.TranslateSegmentationRulesSet, ['name']],
  [Command.TranslateSegmentMerge, ['windowId', 'segmentIndexes']],
  [Command.TranslateSegmentSplit, ['windowId', 'segmentIndex', 'offset']],
  [Command.TranslateTermExtract, ['windowId']],
  [Command.TranslateProofreadRun, ['panelId']],
  [Command.TranslateProofreadApply, ['panelId', 'findingIds']],
  [Command.TranslateConsistencyCheck, ['windowId']],
  [Command.TranslateQaProfileSet, ['name', 'checks']],
  [Command.TranslateQaProfileDelete, ['profileId']],
  [Command.TranslateApprovalSet, ['panelId', 'stage']],
  [Command.TranslateDocumentLoad, ['windowId']],
  [Command.TranslateDocumentRender, ['documentId', 'panelId']],
  [Command.TranslateDocumentLayoutCompare, ['documentId', 'panelId']],
  [Command.TranslateResourceImport, ['windowId', 'path']],
  [Command.TranslateResourceExport, ['resourceId', 'panelId', 'path']],
  [Command.TranslateResourcePluralApply, ['resourceId', 'panelId']],
  [Command.TranslateResourceKeyContextSet, ['resourceId', 'key']],
  [Command.TranslateXliffImport, ['windowId', 'path']],
  [Command.TranslateSubtitleImport, ['windowId', 'path']],
  [Command.TranslateSubtitleExport, ['panelId', 'path', 'format']],
  [Command.TranslateSubtitleTimingCheck, ['panelId']],
  [Command.TranslateDubbingScriptBuild, ['panelId']],
  [Command.TranslateBatchRun, ['windowId', 'operations']],
  [Command.TranslateEngineProfileSet, ['name']],
  [Command.TranslateEngineCompare, ['panelId', 'segment', 'channelIds']],
  [Command.TranslateHandoffBuild, ['windowId', 'contents']],
  [Command.TranslateHandoffReceive, ['windowId', 'path']],
  [Command.TranslateBridgeSourceReceive, ['windowId', 'documentId', 'text']],
  [Command.TranslateBridgeResultSend, ['windowId', 'panelIds', 'mode']],
  [Command.TranslateArtifactPublish, ['windowId', 'kind']],
  [Command.WorkspaceAgentUnassign, ['projectId', 'agentId']],
  [Command.WorkspaceProjectStatusSet, ['projectId', 'status']],
  [Command.WorkspaceInstructionsVersionList, ['projectId']],
  [Command.WorkspaceInstructionsVersionRestore, ['projectId', 'versionId']],
  [Command.WorkspaceTaskCreate, ['projectId', 'title']],
  [Command.WorkspaceTaskUpdate, ['taskId']],
  [Command.WorkspaceTaskDelete, ['taskId']],
  [Command.WorkspaceTaskList, ['projectId']],
  [Command.WorkspaceTaskMove, ['taskId']],
  [Command.WorkspaceTaskDependencySet, ['projectId', 'predecessorTaskId', 'successorTaskId']],
  [Command.WorkspaceTaskDependencyRemove, ['dependencyId']],
  [Command.WorkspaceBoardGet, ['projectId']],
  [Command.WorkspaceScheduleGet, ['projectId']],
  [Command.WorkspaceCalendarGet, ['projectId', 'span', 'anchorAt']],
  [Command.WorkspaceCalendarImport, ['projectId', 'content']],
  [Command.WorkspaceCalendarExport, ['projectId']],
  [Command.WorkspaceNoteSave, ['projectId', 'title', 'content']],
  [Command.WorkspaceNoteGet, ['noteId']],
  [Command.WorkspaceNoteList, ['projectId']],
  [Command.WorkspaceNoteDelete, ['noteId']],
  [Command.WorkspaceNoteTreeGet, ['projectId']],
  [Command.WorkspaceNoteBacklinkList, ['noteId']],
  [Command.WorkspaceKnowledgeGraphGet, ['projectId']],
  [Command.WorkspaceCanvasGet, ['projectId']],
  [Command.WorkspaceCanvasSave, ['projectId', 'scene']],
  [Command.WorkspaceLibraryTextExtract, ['projectId', 'fileId']],
  [Command.WorkspaceLibraryDuplicateList, ['projectId']],
  [Command.WorkspaceLibraryDuplicateMerge, ['projectId', 'keepFileId', 'mergedFileIds']],
  [Command.WorkspaceSearchProject, ['projectId', 'query']],
  [Command.WorkspaceActivityList, ['projectId']],
  [Command.WorkspaceCommentAdd, ['projectId', 'targetKind', 'targetId', 'content']],
  [Command.WorkspaceCommentList, ['projectId']],
  [Command.WorkspaceCommentDelete, ['commentId']],
  [Command.LibraryMetadataGet, ['fileId']],
  [Command.LibraryMetadataSet, ['fileId', 'metadata']],
  [Command.LibrarySchemaSet, ['field']],
  [Command.LibraryTagUpdate, ['name']],
  [Command.LibraryTagMerge, ['sourceNames', 'targetName']],
  [Command.LibraryTagRemove, ['name']],
  [Command.LibraryThesaurusRelate, ['sourceName', 'targetName', 'relation']],
  [Command.LibraryRuleSet, ['rule']],
  [Command.LibraryRuleRemove, ['ruleId']],
  [Command.LibraryDuplicateMerge, ['targetFileId', 'sourceFileIds']],
  [Command.LibraryRetentionSet, ['policy']],
  [Command.LibraryPreservationRun, ['kind']],
  [Command.LibraryPackageExport, ['kind']],
  [Command.LibraryFileMove, ['fileIds', 'path']],
  [Command.LibraryFileArchive, ['fileIds']],
  [Command.LibraryFileRestore, ['fileIds']],
  [Command.LibraryFileDelete, ['fileIds', 'confirm']],
  [Command.LibraryShareCreate, ['scope', 'targetId']],
  [Command.LibraryShareRevoke, ['shareId']],
  [Command.LibraryWebhookSet, ['webhook']],
  [Command.LibraryWebhookRemove, ['webhookId']],
  [Command.LibrarySuggestionApply, ['suggestionIds', 'accept']],
  [Command.LibraryDiffCompare, ['leftFileId']],
  [Command.DesignVectorPathSet, ['boardId', 'nodes']],
  [Command.DesignVectorPathList, ['boardId']],
  [Command.DesignVectorPathRemove, ['pathId']],
  [Command.DesignVectorShapeAdd, ['boardId', 'kind', 'x', 'y', 'width', 'height']],
  [Command.DesignVectorBoolean, ['pathIds', 'operation']],
  [Command.DesignVectorTextPath, ['boardId', 'text', 'fontFamily', 'fontSize']],
  [Command.DesignVectorSymbolSet, ['boardId', 'name']],
  [Command.DesignVectorSymbolList, ['boardId']],
  [Command.DesignVectorExport, ['boardId', 'target']],
  [Command.DesignFrameSet, ['boardId', 'name']],
  [Command.DesignFrameList, ['boardId']],
  [Command.DesignFrameRemove, ['frameId']],
  [Command.DesignLayoutAuto, ['frameId', 'layout']],
  [Command.DesignConstraintSet, ['frameId', 'constraints']],
  [Command.DesignFrameResizeApply, ['frameId', 'width', 'height']],
  [Command.DesignComponentSave, ['windowId', 'name']],
  [Command.DesignComponentList, ['windowId']],
  [Command.DesignComponentInstanceAdd, ['componentId', 'boardId']],
  [Command.DesignPrototypeLinkSet, ['boardId', 'fromFrameId', 'toFrameId', 'trigger', 'transition']],
  [Command.DesignPrototypeGet, ['boardId']],
  [Command.DesignPrototypeLinkRemove, ['linkId']],
  [Command.DesignMockupGenerate, ['windowId', 'boardId', 'prompt']],
  [Command.DesignMockupImport, ['windowId', 'boardId', 'assetId']],
  [Command.DesignGridSet, ['grid']],
  [Command.DesignColorPaletteGenerate, ['baseColor', 'harmony']],
  [Command.DesignColorPaletteExtract, ['assetId']],
  [Command.DesignColorContrastCheck, ['foreground', 'background']],
  [Command.DesignColorVisionSimulate, ['assetId', 'vision']],
  [Command.DesignColorGradientSet, ['boardId', 'gradient']],
  [Command.DesignColorConvert, ['value']],
  [Command.DesignColorAccessibilityAudit, ['tokenSetId']],
  [Command.DesignIconSet, ['windowId', 'name', 'svg']],
  [Command.DesignIconGenerate, ['windowId', 'concepts']],
  [Command.DesignIconSpriteBuild, ['iconIds', 'kind']],
  [Command.DesignFaviconBuild, ['assetId']],
  [Command.DesignFontPairSuggest, ['windowId']],
  [Command.DesignFontPreview, ['fontFamily']],
  [Command.DesignFontGlyphsGet, ['fontFamily']],
  [Command.DesignTemplateSave, ['windowId', 'name', 'kind', 'width', 'height']],
  [Command.DesignTemplateList, ['windowId']],
  [Command.DesignTemplateApply, ['templateId', 'windowId']],
  [Command.DesignCampaignSetBuild, ['boardId', 'sizes']],
  [Command.DesignStockSearch, ['query', 'windowId']],
  [Command.DesignStockImport, ['provider', 'externalId', 'windowId']],
  [Command.DesignProductMockupRender, ['designAssetId', 'productAssetId', 'x', 'y', 'width', 'height']],
  [Command.DesignPrintProfileSet, ['windowId', 'profile']],
  [Command.DesignPrintProfileList, ['windowId']],
  [Command.DesignPrintExport, ['format']],
  [Command.DesignLargeformatTile, ['assetId', 'tileWidthMm', 'tileHeightMm']],
  [Command.DesignChartRender, ['kind', 'series']],
  [Command.DesignDiagramRender, ['kind', 'nodes']],
  [Command.DesignPhotoCrop, ['assetId']],
  [Command.DesignPhotoTransform, ['assetId']],
  [Command.DesignPhotoResample, ['assetId']],
  [Command.DesignPhotoUpscale, ['assetId', 'factor']],
  [Command.DesignPhotoEnhance, ['assetId']],
  [Command.DesignPhotoColorCorrect, ['assetId']],
  [Command.DesignPhotoFilterApply, ['assetId', 'filter']],
  [Command.DesignPhotoRetouch, ['assetId', 'regions']],
  [Command.DesignPhotoInpaint, ['assetId']],
  [Command.DesignPhotoExpand, ['assetId']],
  [Command.DesignPhotoBackgroundRemove, ['assetId']],
  [Command.DesignPhotoSelectObject, ['assetId', 'point']],
  [Command.DesignPhotoMaskSet, ['assetId', 'maskAssetId']],
  [Command.DesignPhotoLayerComposite, ['layers']],
  [Command.DesignPhotoBatchApply, ['assetIds']],
  [Command.DesignPhotoPresetSave, ['windowId', 'name', 'operations']],
  [Command.DesignPhotoPresetList, ['windowId']],
  [Command.DesignPhotoVectorize, ['assetId']],
  [Command.DesignPhotoMetadataGet, ['assetId']],
  [Command.DesignPhotoHistoryGet, ['assetId']],
  [Command.AodMuteSet, ['muted']],
  [Command.AodSignalReport, ['eventClass', 'text']],
  [Command.MemoryDisableSet, ['scope', 'disabled']],
  [Command.NotificationResolve, ['id']],
  [Command.NotificationSnooze, ['id', 'until']],
  [Command.BrowserAccessibilityAudit, ['windowId']],
  [Command.AppsPerformanceAudit, ['windowId', 'url']],
  [Command.DeveloperApiLoadRun, ['windowId', 'url']],
]);
